<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Z:\source\.nuget\packages\umbraco.cms.tests.integration\17.4.0\contentFiles\any\net10.0\Umbraco.Infrastructure\Services\Importing\CheckboxList-Content-Package.xml" />
    <Content Remove="Z:\source\.nuget\packages\umbraco.cms.tests.integration\17.4.0\contentFiles\any\net10.0\Umbraco.Infrastructure\Services\Importing\CompositionsTestPackage-Random.xml" />
    <Content Remove="Z:\source\.nuget\packages\umbraco.cms.tests.integration\17.4.0\contentFiles\any\net10.0\Umbraco.Infrastructure\Services\Importing\CompositionsTestPackage.xml" />
    <Content Remove="Z:\source\.nuget\packages\umbraco.cms.tests.integration\17.4.0\contentFiles\any\net10.0\Umbraco.Infrastructure\Services\Importing\Dictionary-Package.xml" />
    <Content Remove="Z:\source\.nuget\packages\umbraco.cms.tests.integration\17.4.0\contentFiles\any\net10.0\Umbraco.Infrastructure\Services\Importing\Fanoe-Package.xml" />
    <Content Remove="Z:\source\.nuget\packages\umbraco.cms.tests.integration\17.4.0\contentFiles\any\net10.0\Umbraco.Infrastructure\Services\Importing\InheritedDocTypes-Package.xml" />
    <Content Remove="Z:\source\.nuget\packages\umbraco.cms.tests.integration\17.4.0\contentFiles\any\net10.0\Umbraco.Infrastructure\Services\Importing\MediaTypesAndMedia-Package.xml" />
    <Content Remove="Z:\source\.nuget\packages\umbraco.cms.tests.integration\17.4.0\contentFiles\any\net10.0\Umbraco.Infrastructure\Services\Importing\SingleDocType-WithCleanupPolicy.xml" />
    <Content Remove="Z:\source\.nuget\packages\umbraco.cms.tests.integration\17.4.0\contentFiles\any\net10.0\Umbraco.Infrastructure\Services\Importing\SingleDocType.xml" />
    <Content Remove="Z:\source\.nuget\packages\umbraco.cms.tests.integration\17.4.0\contentFiles\any\net10.0\Umbraco.Infrastructure\Services\Importing\StandardMvc-Package.xml" />
    <Content Remove="Z:\source\.nuget\packages\umbraco.cms.tests.integration\17.4.0\contentFiles\any\net10.0\Umbraco.Infrastructure\Services\Importing\TemplateOnly-Package.xml" />
    <Content Remove="Z:\source\.nuget\packages\umbraco.cms.tests.integration\17.4.0\contentFiles\any\net10.0\Umbraco.Infrastructure\Services\Importing\TemplateOnly-Updated-Package.xml" />
    <Content Remove="Z:\source\.nuget\packages\umbraco.cms.tests.integration\17.4.0\contentFiles\any\net10.0\Umbraco.Infrastructure\Services\Importing\uBlogsy-Package.xml" />
    <Content Remove="Z:\source\.nuget\packages\umbraco.cms.tests.integration\17.4.0\contentFiles\any\net10.0\Umbraco.Infrastructure\Services\Importing\XsltSearch-Package.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.10" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="NUnit" Version="4.6.1" />
    <PackageReference Include="NUnit.Analyzers" Version="4.14.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageReference Include="Umbraco.Cms.Tests.Integration" Version="18.1.0" />
    <PackageReference Include="Umbraco.Cms.Persistence.Sqlite" Version="18.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WysiwgUmbracoCommunityExtensionsUmb17\WysiwgUmbracoCommunityExtensionsUmb17.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.Tests.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

</Project>
