// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetAllComponentsData, GetAllComponentsErrors, GetAllComponentsResponses, GetCropsData, GetCropsErrors, GetCropsResponses, GetCropUrlData, GetCropUrlErrors, GetCropUrlResponses, GetFixUpgradeData, GetFixUpgradeErrors, GetFixUpgradeResponses, GetImageUrlData, GetImageUrlErrors, GetImageUrlResponses, GetInstallData, GetInstallErrors, GetInstallResponses, GetMediaTypesData, GetMediaTypesErrors, GetMediaTypesResponses, GetSiteBackgroundColorData, GetSiteBackgroundColorErrors, GetSiteBackgroundColorResponses, GetUnInstallData, GetUnInstallErrors, GetUnInstallResponses, GetUpdateStatusCodeData, GetUpdateStatusCodeErrors, GetUpdateStatusCodeResponses, GetV2CropUrlData, GetV2CropUrlErrors, GetV2CropUrlResponses, GetVariationsData, GetVariationsErrors, GetVariationsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getAllComponents = <ThrowOnError extends boolean = false>(options?: Options<GetAllComponentsData, ThrowOnError>): RequestResult<GetAllComponentsResponses, GetAllComponentsErrors, ThrowOnError> => (options?.client ?? client).get<GetAllComponentsResponses, GetAllComponentsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/wysiwg/all-components',
    ...options
});

export const getCrops = <ThrowOnError extends boolean = false>(options?: Options<GetCropsData, ThrowOnError>): RequestResult<GetCropsResponses, GetCropsErrors, ThrowOnError> => (options?.client ?? client).get<GetCropsResponses, GetCropsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/wysiwg/crops',
    ...options
});

export const getCropUrl = <ThrowOnError extends boolean = false>(options?: Options<GetCropUrlData, ThrowOnError>): RequestResult<GetCropUrlResponses, GetCropUrlErrors, ThrowOnError> => (options?.client ?? client).get<GetCropUrlResponses, GetCropUrlErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/wysiwg/cropurl',
    ...options
});

export const getImageUrl = <ThrowOnError extends boolean = false>(options?: Options<GetImageUrlData, ThrowOnError>): RequestResult<GetImageUrlResponses, GetImageUrlErrors, ThrowOnError> => (options?.client ?? client).get<GetImageUrlResponses, GetImageUrlErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/wysiwg/imageurl',
    ...options
});

export const getV2CropUrl = <ThrowOnError extends boolean = false>(options?: Options<GetV2CropUrlData, ThrowOnError>): RequestResult<GetV2CropUrlResponses, GetV2CropUrlErrors, ThrowOnError> => (options?.client ?? client).get<GetV2CropUrlResponses, GetV2CropUrlErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/wysiwg/v2-cropurl',
    ...options
});

export const getMediaTypes = <ThrowOnError extends boolean = false>(options?: Options<GetMediaTypesData, ThrowOnError>): RequestResult<GetMediaTypesResponses, GetMediaTypesErrors, ThrowOnError> => (options?.client ?? client).get<GetMediaTypesResponses, GetMediaTypesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/wysiwg/mediatypes',
    ...options
});

export const getSiteBackgroundColor = <ThrowOnError extends boolean = false>(options?: Options<GetSiteBackgroundColorData, ThrowOnError>): RequestResult<GetSiteBackgroundColorResponses, GetSiteBackgroundColorErrors, ThrowOnError> => (options?.client ?? client).get<GetSiteBackgroundColorResponses, GetSiteBackgroundColorErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/wysiwg/site-background-color',
    ...options
});

export const getFixUpgrade = <ThrowOnError extends boolean = false>(options?: Options<GetFixUpgradeData, ThrowOnError>): RequestResult<GetFixUpgradeResponses, GetFixUpgradeErrors, ThrowOnError> => (options?.client ?? client).get<GetFixUpgradeResponses, GetFixUpgradeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/wysiwg/fixupgrade',
    ...options
});

export const getInstall = <ThrowOnError extends boolean = false>(options?: Options<GetInstallData, ThrowOnError>): RequestResult<GetInstallResponses, GetInstallErrors, ThrowOnError> => (options?.client ?? client).get<GetInstallResponses, GetInstallErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/wysiwg/install',
    ...options
});

export const getUnInstall = <ThrowOnError extends boolean = false>(options?: Options<GetUnInstallData, ThrowOnError>): RequestResult<GetUnInstallResponses, GetUnInstallErrors, ThrowOnError> => (options?.client ?? client).get<GetUnInstallResponses, GetUnInstallErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/wysiwg/uninstall',
    ...options
});

export const getVariations = <ThrowOnError extends boolean = false>(options?: Options<GetVariationsData, ThrowOnError>): RequestResult<GetVariationsResponses, GetVariationsErrors, ThrowOnError> => (options?.client ?? client).get<GetVariationsResponses, GetVariationsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/wysiwg/variations',
    ...options
});

export const getUpdateStatusCode = <ThrowOnError extends boolean = false>(options?: Options<GetUpdateStatusCodeData, ThrowOnError>): RequestResult<GetUpdateStatusCodeResponses, GetUpdateStatusCodeErrors, ThrowOnError> => (options?.client ?? client).get<GetUpdateStatusCodeResponses, GetUpdateStatusCodeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/wysiwg/updateStatusCode',
    ...options
});
