// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetCropsData, GetCropsErrors, GetCropsResponses, GetCropurlData, GetCropurlErrors, GetCropurlResponses, GetFixupgradeData, GetFixupgradeErrors, GetFixupgradeResponses, GetImageurlData, GetImageurlErrors, GetImageurlResponses, GetInstallData, GetInstallErrors, GetInstallResponses, GetMediatypesData, GetMediatypesErrors, GetMediatypesResponses, GetSiteBackgroundColorData, GetSiteBackgroundColorResponses, GetUninstallData, GetUninstallResponses, GetUpdateStatusCodeData, GetUpdateStatusCodeErrors, GetUpdateStatusCodeResponses, GetV2CropurlData, GetV2CropurlErrors, GetV2CropurlResponses, GetVariationsData, GetVariationsErrors, GetVariationsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getCrops = <ThrowOnError extends boolean = false>(options?: Options<GetCropsData, ThrowOnError>) => (options?.client ?? client).get<GetCropsResponses, GetCropsErrors, ThrowOnError>({ url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/crops', ...options });

export const getCropurl = <ThrowOnError extends boolean = false>(options?: Options<GetCropurlData, ThrowOnError>) => (options?.client ?? client).get<GetCropurlResponses, GetCropurlErrors, ThrowOnError>({ url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/cropurl', ...options });

export const getFixupgrade = <ThrowOnError extends boolean = false>(options?: Options<GetFixupgradeData, ThrowOnError>) => (options?.client ?? client).get<GetFixupgradeResponses, GetFixupgradeErrors, ThrowOnError>({ url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/fixupgrade', ...options });

export const getImageurl = <ThrowOnError extends boolean = false>(options?: Options<GetImageurlData, ThrowOnError>) => (options?.client ?? client).get<GetImageurlResponses, GetImageurlErrors, ThrowOnError>({ url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/imageurl', ...options });

export const getInstall = <ThrowOnError extends boolean = false>(options?: Options<GetInstallData, ThrowOnError>) => (options?.client ?? client).get<GetInstallResponses, GetInstallErrors, ThrowOnError>({ url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/install', ...options });

export const getMediatypes = <ThrowOnError extends boolean = false>(options?: Options<GetMediatypesData, ThrowOnError>) => (options?.client ?? client).get<GetMediatypesResponses, GetMediatypesErrors, ThrowOnError>({ url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/mediatypes', ...options });

export const getSiteBackgroundColor = <ThrowOnError extends boolean = false>(options?: Options<GetSiteBackgroundColorData, ThrowOnError>) => (options?.client ?? client).get<GetSiteBackgroundColorResponses, unknown, ThrowOnError>({ url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/site-background-color', ...options });

export const getUninstall = <ThrowOnError extends boolean = false>(options?: Options<GetUninstallData, ThrowOnError>) => (options?.client ?? client).get<GetUninstallResponses, unknown, ThrowOnError>({ url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/uninstall', ...options });

export const getUpdateStatusCode = <ThrowOnError extends boolean = false>(options?: Options<GetUpdateStatusCodeData, ThrowOnError>) => (options?.client ?? client).get<GetUpdateStatusCodeResponses, GetUpdateStatusCodeErrors, ThrowOnError>({ url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/updateStatusCode', ...options });

export const getV2Cropurl = <ThrowOnError extends boolean = false>(options?: Options<GetV2CropurlData, ThrowOnError>) => (options?.client ?? client).get<GetV2CropurlResponses, GetV2CropurlErrors, ThrowOnError>({ url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/v2-cropurl', ...options });

export const getVariations = <ThrowOnError extends boolean = false>(options?: Options<GetVariationsData, ThrowOnError>) => (options?.client ?? client).get<GetVariationsResponses, GetVariationsErrors, ThrowOnError>({ url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/variations', ...options });
