// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44313/' | (string & {});
};

export type BlockItemDataModel = {
    contentTypeKey: string;
    key: string;
    values: Array<BlockPropertyValueModel>;
};

export type BlockPropertyValueModel = {
    editorAlias?: null | string;
    culture?: null | string;
    segment?: null | string;
    alias: string;
    value?: unknown;
};

export type ComponentPickerOption = {
    name?: null | string;
    value?: null | string;
    selected: boolean;
};

export type ContentTypeSortModel = {
    sortOrder: number | string;
    alias: string;
    key: string;
};

export type ContentVariationModel = number;

export type IContentTypeCompositionModel = {
    contentTypeComposition: Array<IContentTypeCompositionModel>;
    compositionPropertyGroups: null | Array<PropertyGroupModel>;
    compositionPropertyTypes: null | Array<IPropertyTypeModel>;
    removedContentTypes: null | Array<number | string>;
    alias: string;
    description?: null | string;
    icon?: null | string;
    thumbnail?: null | string;
    allowedAsRoot: boolean;
    listView?: null | string;
    isElement: boolean;
    allowedInLibrary: boolean;
    variations: ContentVariationModel;
    allowedContentTypes?: null | Array<ContentTypeSortModel>;
    propertyGroups: Array<PropertyGroupModel>;
    propertyTypes: null | Array<IPropertyTypeModel>;
    noGroupPropertyTypes: Array<IPropertyTypeModel>;
    name?: null | string;
    creatorId: number | string;
    parentId: number | string;
    level: number | string;
    path: string;
    sortOrder: number | string;
    trashed: boolean;
    id: number | string;
    key: string;
    createDate: string;
    updateDate: string;
    deleteDate?: null | string;
    hasIdentity: boolean;
};

export type ImageCropperCropCoordinatesModel = {
    x1: number | string;
    y1: number | string;
    x2: number | string;
    y2: number | string;
};

export type ImageCropperCropModel = {
    alias?: null | string;
    width: number | string;
    height: number | string;
    coordinates?: null | ImageCropperCropCoordinatesModel;
};

export type IMediaTypeModel = {
    contentTypeComposition: Array<IContentTypeCompositionModel>;
    compositionPropertyGroups: null | Array<PropertyGroupModel>;
    compositionPropertyTypes: null | Array<IPropertyTypeModel>;
    removedContentTypes: null | Array<number | string>;
    alias: string;
    description?: null | string;
    icon?: null | string;
    thumbnail?: null | string;
    allowedAsRoot: boolean;
    listView?: null | string;
    isElement: boolean;
    allowedInLibrary: boolean;
    variations: ContentVariationModel;
    allowedContentTypes?: null | Array<ContentTypeSortModel>;
    propertyGroups: Array<PropertyGroupModel>;
    propertyTypes: null | Array<IPropertyTypeModel>;
    noGroupPropertyTypes: Array<IPropertyTypeModel>;
    name?: null | string;
    creatorId: number | string;
    parentId: number | string;
    level: number | string;
    path: string;
    sortOrder: number | string;
    trashed: boolean;
    id: number | string;
    key: string;
    createDate: string;
    updateDate: string;
    deleteDate?: null | string;
    hasIdentity: boolean;
};

export type IPropertyTypeModel = {
    name: string;
    alias: string;
    description?: null | string;
    dataTypeId: number | string;
    dataTypeKey: string;
    propertyEditorAlias: string;
    valueStorageType: ValueStorageTypeModel;
    propertyGroupId?: null | LazyOfint;
    mandatory: boolean;
    labelOnTop: boolean;
    sortOrder: number | string;
    validationRegExp?: null | string;
    supportsPublishing: boolean;
    variations: ContentVariationModel;
    mandatoryMessage?: null | string;
    validationRegExpMessage?: null | string;
    id: number | string;
    key: string;
    createDate: string;
    updateDate: string;
    deleteDate?: null | string;
    hasIdentity: boolean;
};

export type LazyOfint = {
    isValueCreated: boolean;
    value: number | string;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
};

export type PropertyGroupModel = {
    type: PropertyGroupTypeModel;
    name?: null | string;
    alias: string;
    sortOrder: number | string;
    propertyTypes?: null | Array<IPropertyTypeModel>;
    id: number | string;
    key: string;
    createDate: string;
    updateDate: string;
    deleteDate?: null | string;
    hasIdentity: boolean;
};

export type PropertyGroupTypeModel = number;

export type RequestPreviewMarkupModel = {
    data?: null | BlockItemDataModel;
    pageKey?: null | string;
    culture?: null | string;
};

export type ValueStorageTypeModel = number;

export type GetAllComponentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/wysiwg/all-components';
};

export type GetAllComponentsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetAllComponentsResponses = {
    /**
     * OK
     */
    200: Array<ComponentPickerOption>;
};

export type GetAllComponentsResponse = GetAllComponentsResponses[keyof GetAllComponentsResponses];

export type PostWysiwgPreviewMarkupData = {
    body: RequestPreviewMarkupModel;
    path?: never;
    query?: never;
    url: '/api/v1/wysiwg/preview-markup';
};

export type PostWysiwgPreviewMarkupErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostWysiwgPreviewMarkupError = PostWysiwgPreviewMarkupErrors[keyof PostWysiwgPreviewMarkupErrors];

export type PostWysiwgPreviewMarkupResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostWysiwgPreviewMarkupResponse = PostWysiwgPreviewMarkupResponses[keyof PostWysiwgPreviewMarkupResponses];

export type GetCropsData = {
    body?: never;
    path?: never;
    query?: {
        mediaItemId?: string;
    };
    url: '/api/v1/wysiwg/crops';
};

export type GetCropsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: Array<ImageCropperCropModel>;
};

export type GetCropsError = GetCropsErrors[keyof GetCropsErrors];

export type GetCropsResponses = {
    /**
     * OK
     */
    200: Array<ImageCropperCropModel>;
};

export type GetCropsResponse = GetCropsResponses[keyof GetCropsResponses];

export type GetCropUrlData = {
    body?: never;
    path?: never;
    query?: {
        mediaItemId?: string;
        cropAlias?: string;
        width?: number | string;
    };
    url: '/api/v1/wysiwg/cropurl';
};

export type GetCropUrlErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: string;
};

export type GetCropUrlError = GetCropUrlErrors[keyof GetCropUrlErrors];

export type GetCropUrlResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetCropUrlResponse = GetCropUrlResponses[keyof GetCropUrlResponses];

export type GetImageUrlData = {
    body?: never;
    path?: never;
    query?: {
        mediaItemId?: string;
    };
    url: '/api/v1/wysiwg/imageurl';
};

export type GetImageUrlErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: string;
};

export type GetImageUrlError = GetImageUrlErrors[keyof GetImageUrlErrors];

export type GetImageUrlResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetImageUrlResponse = GetImageUrlResponses[keyof GetImageUrlResponses];

export type GetV2CropUrlData = {
    body?: never;
    path?: never;
    query?: {
        mediaItemId?: string;
        cropAlias?: string;
        selectedCrop?: string;
        width?: number | string;
        selectedFocalPoint?: string;
    };
    url: '/api/v1/wysiwg/v2-cropurl';
};

export type GetV2CropUrlErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: string;
};

export type GetV2CropUrlError = GetV2CropUrlErrors[keyof GetV2CropUrlErrors];

export type GetV2CropUrlResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetV2CropUrlResponse = GetV2CropUrlResponses[keyof GetV2CropUrlResponses];

export type GetMediaTypesData = {
    body?: never;
    path?: never;
    query?: {
        name?: string;
    };
    url: '/api/v1/wysiwg/mediatypes';
};

export type GetMediaTypesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: Array<IMediaTypeModel>;
};

export type GetMediaTypesError = GetMediaTypesErrors[keyof GetMediaTypesErrors];

export type GetMediaTypesResponses = {
    /**
     * OK
     */
    200: Array<IMediaTypeModel>;
};

export type GetMediaTypesResponse = GetMediaTypesResponses[keyof GetMediaTypesResponses];

export type GetSiteBackgroundColorData = {
    body?: never;
    path?: never;
    query?: {
        pageKey?: string;
    };
    url: '/api/v1/wysiwg/site-background-color';
};

export type GetSiteBackgroundColorErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetSiteBackgroundColorResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetSiteBackgroundColorResponse = GetSiteBackgroundColorResponses[keyof GetSiteBackgroundColorResponses];

export type GetFixUpgradeData = {
    body?: never;
    path?: never;
    query?: {
        culture?: boolean;
        segment?: boolean;
    };
    url: '/api/v1/wysiwg/fixupgrade';
};

export type GetFixUpgradeErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Internal Server Error
     */
    500: string;
};

export type GetFixUpgradeError = GetFixUpgradeErrors[keyof GetFixUpgradeErrors];

export type GetFixUpgradeResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetFixUpgradeResponse = GetFixUpgradeResponses[keyof GetFixUpgradeResponses];

export type GetInstallData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/wysiwg/install';
};

export type GetInstallErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Internal Server Error
     */
    500: string;
};

export type GetInstallError = GetInstallErrors[keyof GetInstallErrors];

export type GetInstallResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetInstallResponse = GetInstallResponses[keyof GetInstallResponses];

export type GetUnInstallData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/wysiwg/uninstall';
};

export type GetUnInstallErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetUnInstallResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetUnInstallResponse = GetUnInstallResponses[keyof GetUnInstallResponses];

export type GetVariationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/wysiwg/variations';
};

export type GetVariationsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Internal Server Error
     */
    500: string;
};

export type GetVariationsError = GetVariationsErrors[keyof GetVariationsErrors];

export type GetVariationsResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetVariationsResponse = GetVariationsResponses[keyof GetVariationsResponses];

export type GetUpdateStatusCodeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/wysiwg/updateStatusCode';
};

export type GetUpdateStatusCodeErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Internal Server Error
     */
    500: number | string;
};

export type GetUpdateStatusCodeError = GetUpdateStatusCodeErrors[keyof GetUpdateStatusCodeErrors];

export type GetUpdateStatusCodeResponses = {
    /**
     * OK
     */
    200: number | string;
};

export type GetUpdateStatusCodeResponse = GetUpdateStatusCodeResponses[keyof GetUpdateStatusCodeResponses];
