// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44313/' | (string & {});
};

export type ContentTypeSortModel = {
    sortOrder: number | string;
    alias: string;
    key: string;
};

export type ContentVariationModel = number;

export type IContentTypeCompositionModel = {
    contentTypeComposition: Array<IContentTypeCompositionModel>;
    compositionPropertyGroups: null | Array<PropertyGroupModel>;
    compositionPropertyTypes: null | Array<IPropertyTypeModel>;
    removedContentTypes: null | Array<number | string>;
    alias: string;
    description?: null | string;
    icon?: null | string;
    thumbnail?: null | string;
    allowedAsRoot: boolean;
    listView?: null | string;
    isElement: boolean;
    allowedInLibrary: boolean;
    variations: ContentVariationModel;
    allowedContentTypes?: null | Array<ContentTypeSortModel>;
    propertyGroups: Array<PropertyGroupModel>;
    propertyTypes: null | Array<IPropertyTypeModel>;
    noGroupPropertyTypes: Array<IPropertyTypeModel>;
    name?: null | string;
    creatorId: number | string;
    parentId: number | string;
    level: number | string;
    path: string;
    sortOrder: number | string;
    trashed: boolean;
    id: number | string;
    key: string;
    createDate: string;
    updateDate: string;
    deleteDate?: null | string;
    hasIdentity: boolean;
};

export type ImageCropperCropCoordinatesModel = {
    x1: number | string;
    y1: number | string;
    x2: number | string;
    y2: number | string;
};

export type ImageCropperCropModel = {
    alias?: null | string;
    width: number | string;
    height: number | string;
    coordinates?: null | ImageCropperCropCoordinatesModel;
};

export type IMediaTypeModel = {
    contentTypeComposition: Array<IContentTypeCompositionModel>;
    compositionPropertyGroups: null | Array<PropertyGroupModel>;
    compositionPropertyTypes: null | Array<IPropertyTypeModel>;
    removedContentTypes: null | Array<number | string>;
    alias: string;
    description?: null | string;
    icon?: null | string;
    thumbnail?: null | string;
    allowedAsRoot: boolean;
    listView?: null | string;
    isElement: boolean;
    allowedInLibrary: boolean;
    variations: ContentVariationModel;
    allowedContentTypes?: null | Array<ContentTypeSortModel>;
    propertyGroups: Array<PropertyGroupModel>;
    propertyTypes: null | Array<IPropertyTypeModel>;
    noGroupPropertyTypes: Array<IPropertyTypeModel>;
    name?: null | string;
    creatorId: number | string;
    parentId: number | string;
    level: number | string;
    path: string;
    sortOrder: number | string;
    trashed: boolean;
    id: number | string;
    key: string;
    createDate: string;
    updateDate: string;
    deleteDate?: null | string;
    hasIdentity: boolean;
};

export type IPropertyTypeModel = {
    name: string;
    alias: string;
    description?: null | string;
    dataTypeId: number | string;
    dataTypeKey: string;
    propertyEditorAlias: string;
    valueStorageType: ValueStorageTypeModel;
    propertyGroupId?: null | LazyOfint;
    mandatory: boolean;
    labelOnTop: boolean;
    sortOrder: number | string;
    validationRegExp?: null | string;
    supportsPublishing: boolean;
    variations: ContentVariationModel;
    mandatoryMessage?: null | string;
    validationRegExpMessage?: null | string;
    id: number | string;
    key: string;
    createDate: string;
    updateDate: string;
    deleteDate?: null | string;
    hasIdentity: boolean;
};

export type LazyOfint = {
    isValueCreated: boolean;
    value: number | string;
};

export type PropertyGroupModel = {
    type: PropertyGroupTypeModel;
    name?: null | string;
    alias: string;
    sortOrder: number | string;
    propertyTypes?: null | Array<IPropertyTypeModel>;
    id: number | string;
    key: string;
    createDate: string;
    updateDate: string;
    deleteDate?: null | string;
    hasIdentity: boolean;
};

export type PropertyGroupTypeModel = number;

export type ValueStorageTypeModel = number;

export type GetCropsData = {
    body?: never;
    path?: never;
    query?: {
        mediaItemId?: string;
    };
    url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/crops';
};

export type GetCropsErrors = {
    /**
     * Not Found
     */
    404: Array<ImageCropperCropModel>;
};

export type GetCropsError = GetCropsErrors[keyof GetCropsErrors];

export type GetCropsResponses = {
    /**
     * OK
     */
    200: Array<ImageCropperCropModel>;
};

export type GetCropsResponse = GetCropsResponses[keyof GetCropsResponses];

export type GetCropurlData = {
    body?: never;
    path?: never;
    query?: {
        mediaItemId?: string;
        cropAlias?: string;
        width?: number | string;
    };
    url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/cropurl';
};

export type GetCropurlErrors = {
    /**
     * Not Found
     */
    404: string;
};

export type GetCropurlError = GetCropurlErrors[keyof GetCropurlErrors];

export type GetCropurlResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetCropurlResponse = GetCropurlResponses[keyof GetCropurlResponses];

export type GetFixupgradeData = {
    body?: never;
    path?: never;
    query?: {
        culture?: boolean;
        segment?: boolean;
    };
    url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/fixupgrade';
};

export type GetFixupgradeErrors = {
    /**
     * Internal Server Error
     */
    500: string;
};

export type GetFixupgradeError = GetFixupgradeErrors[keyof GetFixupgradeErrors];

export type GetFixupgradeResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetFixupgradeResponse = GetFixupgradeResponses[keyof GetFixupgradeResponses];

export type GetImageurlData = {
    body?: never;
    path?: never;
    query?: {
        mediaItemId?: string;
    };
    url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/imageurl';
};

export type GetImageurlErrors = {
    /**
     * Not Found
     */
    404: string;
};

export type GetImageurlError = GetImageurlErrors[keyof GetImageurlErrors];

export type GetImageurlResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetImageurlResponse = GetImageurlResponses[keyof GetImageurlResponses];

export type GetInstallData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/install';
};

export type GetInstallErrors = {
    /**
     * Internal Server Error
     */
    500: string;
};

export type GetInstallError = GetInstallErrors[keyof GetInstallErrors];

export type GetInstallResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetInstallResponse = GetInstallResponses[keyof GetInstallResponses];

export type GetMediatypesData = {
    body?: never;
    path?: never;
    query?: {
        name?: string;
    };
    url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/mediatypes';
};

export type GetMediatypesErrors = {
    /**
     * Not Found
     */
    404: Array<IMediaTypeModel>;
};

export type GetMediatypesError = GetMediatypesErrors[keyof GetMediatypesErrors];

export type GetMediatypesResponses = {
    /**
     * OK
     */
    200: Array<IMediaTypeModel>;
};

export type GetMediatypesResponse = GetMediatypesResponses[keyof GetMediatypesResponses];

export type GetSiteBackgroundColorData = {
    body?: never;
    path?: never;
    query?: {
        pageKey?: string;
    };
    url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/site-background-color';
};

export type GetSiteBackgroundColorResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetSiteBackgroundColorResponse = GetSiteBackgroundColorResponses[keyof GetSiteBackgroundColorResponses];

export type GetUninstallData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/uninstall';
};

export type GetUninstallResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetUninstallResponse = GetUninstallResponses[keyof GetUninstallResponses];

export type GetUpdateStatusCodeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/updateStatusCode';
};

export type GetUpdateStatusCodeErrors = {
    /**
     * Internal Server Error
     */
    500: number | string;
};

export type GetUpdateStatusCodeError = GetUpdateStatusCodeErrors[keyof GetUpdateStatusCodeErrors];

export type GetUpdateStatusCodeResponses = {
    /**
     * OK
     */
    200: number | string;
};

export type GetUpdateStatusCodeResponse = GetUpdateStatusCodeResponses[keyof GetUpdateStatusCodeResponses];

export type GetV2CropurlData = {
    body?: never;
    path?: never;
    query?: {
        mediaItemId?: string;
        cropAlias?: string;
        selectedCrop?: string;
        width?: number | string;
        selectedFocalPoint?: string;
    };
    url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/v2-cropurl';
};

export type GetV2CropurlErrors = {
    /**
     * Not Found
     */
    404: string;
};

export type GetV2CropurlError = GetV2CropurlErrors[keyof GetV2CropurlErrors];

export type GetV2CropurlResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetV2CropurlResponse = GetV2CropurlResponses[keyof GetV2CropurlResponses];

export type GetVariationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/variations';
};

export type GetVariationsErrors = {
    /**
     * Internal Server Error
     */
    500: string;
};

export type GetVariationsError = GetVariationsErrors[keyof GetVariationsErrors];

export type GetVariationsResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetVariationsResponse = GetVariationsResponses[keyof GetVariationsResponses];
