// This file is auto-generated by @hey-api/openapi-ts

export const ImageCropperCropCoordinatesModelSchema = {
    required: ['x1', 'x2', 'y1', 'y2'],
    type: 'object',
    properties: {
        x1: {
            type: 'number',
            format: 'double'
        },
        y1: {
            type: 'number',
            format: 'double'
        },
        x2: {
            type: 'number',
            format: 'double'
        },
        y2: {
            type: 'number',
            format: 'double'
        }
    },
    additionalProperties: false
} as const;

export const ImageCropperCropModelSchema = {
    required: ['height', 'width'],
    type: 'object',
    properties: {
        alias: {
            type: 'string',
            nullable: true
        },
        width: {
            type: 'integer',
            format: 'int32'
        },
        height: {
            type: 'integer',
            format: 'int32'
        },
        coordinates: {
            oneOf: [
                {
                    '$ref': '#/components/schemas/ImageCropperCropCoordinatesModel'
                }
            ],
            nullable: true
        }
    },
    additionalProperties: false
} as const;