// This file is auto-generated by @hey-api/openapi-ts

export type CropUrlData = {
    query?: {
        cropAlias?: string;
        mediaItemId?: string;
        width?: number;
    };
};

export type CropUrlResponse = (string);

export type CropUrlError = (unknown | string);

export type ImageUrlData = {
    query?: {
        mediaItemId?: string;
    };
};

export type ImageUrlResponse = (string);

export type ImageUrlError = (unknown | string);