// This file is auto-generated by @hey-api/openapi-ts

export type ImageCropperCropCoordinatesModel = {
    x1: number;
    y1: number;
    x2: number;
    y2: number;
};

export type ImageCropperCropModel = {
    alias?: (string) | null;
    width: number;
    height: number;
    coordinates?: ((ImageCropperCropCoordinatesModel) | null);
};

export type CropsData = {
    query?: {
        mediaItemId?: string;
    };
};

export type CropsResponse = (Array<(ImageCropperCropModel)>);

export type CropsError = (unknown | Array<(ImageCropperCropModel)>);

export type CropUrlData = {
    query?: {
        cropAlias?: string;
        mediaItemId?: string;
        selectedCrop?: string;
        width?: number;
    };
};

export type CropUrlResponse = (string);

export type CropUrlError = (unknown | string);

export type ImageUrlData = {
    query?: {
        mediaItemId?: string;
    };
};

export type ImageUrlResponse = (string);

export type ImageUrlError = (unknown | string);

export type InstallResponse = (string);

export type InstallError = (unknown | string);

export type UnInstallResponse = (string);

export type UnInstallError = (unknown);