// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetServerConfigurationData, GetServerConfigurationResponses, GetServerInformationData, GetServerInformationErrors, GetServerInformationResponses, GetServerStatusData, GetServerStatusErrors, GetServerStatusResponses, GetServerTroubleshootingData, GetServerTroubleshootingErrors, GetServerTroubleshootingResponses, GetServerUpgradeCheckData, GetServerUpgradeCheckErrors, GetServerUpgradeCheckResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Gets the server configuration.
 *
 * Gets the configuration settings for servers.
 */
export const getServerConfiguration = <ThrowOnError extends boolean = false>(options?: Options<GetServerConfigurationData, ThrowOnError>) => (options?.client ?? client).get<GetServerConfigurationResponses, unknown, ThrowOnError>({ url: '/umbraco/management/api/v1/server/configuration', ...options });

/**
 * Gets server information.
 *
 * Gets detailed information about the server environment and configuration.
 */
export const getServerInformation = <ThrowOnError extends boolean = false>(options?: Options<GetServerInformationData, ThrowOnError>) => (options?.client ?? client).get<GetServerInformationResponses, GetServerInformationErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/server/information',
    ...options
});

/**
 * Gets server status.
 *
 * Gets the current operational status of the Umbraco server.
 */
export const getServerStatus = <ThrowOnError extends boolean = false>(options?: Options<GetServerStatusData, ThrowOnError>) => (options?.client ?? client).get<GetServerStatusResponses, GetServerStatusErrors, ThrowOnError>({ url: '/umbraco/management/api/v1/server/status', ...options });

/**
 * Gets server troubleshooting information.
 *
 * Gets troubleshooting information and diagnostics for the server.
 */
export const getServerTroubleshooting = <ThrowOnError extends boolean = false>(options?: Options<GetServerTroubleshootingData, ThrowOnError>) => (options?.client ?? client).get<GetServerTroubleshootingResponses, GetServerTroubleshootingErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/server/troubleshooting',
    ...options
});

/**
 * Checks for available upgrades.
 *
 * Checks if there are any available upgrades for the Umbraco installation.
 */
export const getServerUpgradeCheck = <ThrowOnError extends boolean = false>(options?: Options<GetServerUpgradeCheckData, ThrowOnError>) => (options?.client ?? client).get<GetServerUpgradeCheckResponses, GetServerUpgradeCheckErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/server/upgrade-check',
    ...options
});
