// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AllowedDocumentTypeModel = {
    id: string;
    name: string;
    description?: null | string;
    icon?: null | string;
};

export type AllowedMediaTypeItemResponseModel = {
    matchedFileExtension: boolean;
    icon?: null | string;
    name: string;
    id: string;
    flags: Array<FlagModel>;
};

export type AllowedMediaTypeModel = {
    id: string;
    name: string;
    description?: null | string;
    icon?: null | string;
};

export type AllowedMemberTypeModel = {
    id: string;
    name: string;
    description?: null | string;
    icon?: null | string;
};

export type AuditLogResponseModel = {
    user: ReferenceByIdModel;
    timestamp: string;
    logType: AuditTypeModel;
    comment?: null | string;
    parameters?: null | string;
};

export type AuditTypeModel = 'New' | 'Save' | 'SaveVariant' | 'Open' | 'Delete' | 'Publish' | 'PublishVariant' | 'SendToPublish' | 'SendToPublishVariant' | 'Unpublish' | 'UnpublishVariant' | 'Move' | 'Copy' | 'AssignDomain' | 'PublicAccess' | 'Sort' | 'Notify' | 'System' | 'RollBack' | 'PackagerInstall' | 'PackagerUninstall' | 'Custom' | 'ContentVersionPreventCleanup' | 'ContentVersionEnableCleanup';

export type AvailableDocumentTypeCompositionResponseModel = {
    folderPath: Array<string>;
    isCompatible: boolean;
    id: string;
    name: string;
    icon: string;
};

export type AvailableMediaTypeCompositionResponseModel = {
    folderPath: Array<string>;
    isCompatible: boolean;
    id: string;
    name: string;
    icon: string;
};

export type AvailableMemberTypeCompositionResponseModel = {
    folderPath: Array<string>;
    isCompatible: boolean;
    id: string;
    name: string;
    icon: string;
};

export type BatchResponseModelDataTypeResponseModel = {
    total: number;
    items: Array<DataTypeResponseModel>;
};

export type BatchResponseModelDocumentTypeResponseModel = {
    total: number;
    items: Array<DocumentTypeResponseModel>;
};

export type BatchResponseModelMediaTypeResponseModel = {
    total: number;
    items: Array<MediaTypeResponseModel>;
};

export type BatchResponseModelMemberTypeResponseModel = {
    total: number;
    items: Array<MemberTypeResponseModel>;
};

export type CalculatedUserStartNodesResponseModel = {
    id: string;
    documentStartNodeIds: Array<ReferenceByIdModel>;
    hasDocumentRootAccess: boolean;
    mediaStartNodeIds: Array<ReferenceByIdModel>;
    hasMediaRootAccess: boolean;
    elementStartNodeIds: Array<ReferenceByIdModel>;
    hasElementRootAccess: boolean;
};

export type ChangePasswordCurrentUserRequestModel = {
    oldPassword?: null | string;
    newPassword: string;
};

export type ChangePasswordUserRequestModel = {
    newPassword: string;
};

export type CompositionTypeModel = 'Composition' | 'Inheritance';

export type ConsentLevelPresentationModel = {
    level: TelemetryLevelModel;
    description: string;
};

export type CopyDataTypeRequestModel = {
    target?: null | ReferenceByIdModel;
};

export type CopyDocumentRequestModel = {
    target?: null | ReferenceByIdModel;
    relateToOriginal: boolean;
    includeDescendants: boolean;
};

export type CopyDocumentTypeRequestModel = {
    target?: null | ReferenceByIdModel;
};

export type CopyElementRequestModel = {
    target?: null | ReferenceByIdModel;
};

export type CopyMediaTypeRequestModel = {
    target?: null | ReferenceByIdModel;
};

export type CopyMemberTypeRequestModel = {
    target?: null | ReferenceByIdModel;
};

export type CreateDataTypeRequestModel = {
    id?: null | string;
    parent?: null | ReferenceByIdModel;
    name: string;
    editorAlias: string;
    editorUiAlias: string;
    values: Array<DataTypePropertyPresentationModel>;
};

export type CreateDictionaryItemRequestModel = {
    id?: null | string;
    parent?: null | ReferenceByIdModel;
    name: string;
    translations: Array<DictionaryItemTranslationModel>;
};

export type CreateDocumentBlueprintFromDocumentRequestModel = {
    document: ReferenceByIdModel;
    id?: null | string;
    name: string;
    parent?: null | ReferenceByIdModel;
};

export type CreateDocumentBlueprintRequestModel = {
    documentType: ReferenceByIdModel;
    parent?: null | ReferenceByIdModel;
    id?: null | string;
    values: Array<DocumentValueModel>;
    variants: Array<DocumentVariantRequestModel>;
};

export type CreateDocumentRequestModel = {
    template: null | ReferenceByIdModel;
    documentType: ReferenceByIdModel;
    parent?: null | ReferenceByIdModel;
    id?: null | string;
    values: Array<DocumentValueModel>;
    variants: Array<DocumentVariantRequestModel>;
};

export type CreateDocumentTypePropertyTypeContainerRequestModel = {
    id: string;
    parent?: null | ReferenceByIdModel;
    name?: null | string;
    type: string;
    sortOrder: number;
};

export type CreateDocumentTypePropertyTypeRequestModel = {
    id: string;
    container?: null | ReferenceByIdModel;
    sortOrder: number;
    alias: string;
    name: string;
    description?: null | string;
    dataType: ReferenceByIdModel;
    variesByCulture: boolean;
    variesBySegment: boolean;
    validation: PropertyTypeValidationModel;
    appearance: PropertyTypeAppearanceModel;
};

export type CreateDocumentTypeRequestModel = {
    allowedTemplates: Array<ReferenceByIdModel>;
    defaultTemplate?: null | ReferenceByIdModel;
    cleanup: DocumentTypeCleanupModel;
    allowedDocumentTypes: Array<DocumentTypeSortModel>;
    compositions: Array<DocumentTypeCompositionModel>;
    parent?: null | ReferenceByIdModel;
    id?: null | string;
    alias: string;
    name: string;
    description?: null | string;
    icon: string;
    allowedAsRoot: boolean;
    variesByCulture: boolean;
    variesBySegment: boolean;
    collection?: null | ReferenceByIdModel;
    isElement: boolean;
    allowedInLibrary: boolean;
    properties: Array<CreateDocumentTypePropertyTypeRequestModel>;
    containers: Array<CreateDocumentTypePropertyTypeContainerRequestModel>;
};

export type CreateDocumentTypeTemplateRequestModel = {
    alias: string;
    name: string;
    isDefault: boolean;
};

export type CreateElementRequestModel = {
    documentType: ReferenceByIdModel;
    parent?: null | ReferenceByIdModel;
    id?: null | string;
    values: Array<ElementValueModel>;
    variants: Array<ElementVariantRequestModel>;
};

export type CreateFolderRequestModel = {
    id?: null | string;
    parent?: null | ReferenceByIdModel;
    name: string;
};

export type CreateInitialPasswordUserRequestModel = {
    password: string;
    user: ReferenceByIdModel;
    token: string;
};

export type CreateLanguageRequestModel = {
    isoCode: string;
    name: string;
    isDefault: boolean;
    isMandatory: boolean;
    fallbackIsoCode?: null | string;
};

export type CreateMediaRequestModel = {
    mediaType: ReferenceByIdModel;
    parent?: null | ReferenceByIdModel;
    id?: null | string;
    values: Array<MediaValueModel>;
    variants: Array<MediaVariantRequestModel>;
};

export type CreateMediaTypePropertyTypeContainerRequestModel = {
    id: string;
    parent?: null | ReferenceByIdModel;
    name?: null | string;
    type: string;
    sortOrder: number;
};

export type CreateMediaTypePropertyTypeRequestModel = {
    id: string;
    container?: null | ReferenceByIdModel;
    sortOrder: number;
    alias: string;
    name: string;
    description?: null | string;
    dataType: ReferenceByIdModel;
    variesByCulture: boolean;
    variesBySegment: boolean;
    validation: PropertyTypeValidationModel;
    appearance: PropertyTypeAppearanceModel;
};

export type CreateMediaTypeRequestModel = {
    allowedMediaTypes: Array<MediaTypeSortModel>;
    compositions: Array<MediaTypeCompositionModel>;
    parent?: null | ReferenceByIdModel;
    id?: null | string;
    alias: string;
    name: string;
    description?: null | string;
    icon: string;
    allowedAsRoot: boolean;
    variesByCulture: boolean;
    variesBySegment: boolean;
    collection?: null | ReferenceByIdModel;
    isElement: boolean;
    allowedInLibrary: boolean;
    properties: Array<CreateMediaTypePropertyTypeRequestModel>;
    containers: Array<CreateMediaTypePropertyTypeContainerRequestModel>;
};

export type CreateMemberGroupRequestModel = {
    id?: null | string;
    name: string;
};

export type CreateMemberRequestModel = {
    email: string;
    username: string;
    password: string;
    memberType: ReferenceByIdModel;
    groups?: null | Array<string>;
    isApproved: boolean;
    id?: null | string;
    values: Array<MemberValueModel>;
    variants: Array<MemberVariantRequestModel>;
};

export type CreateMemberTypePropertyTypeContainerRequestModel = {
    id: string;
    parent?: null | ReferenceByIdModel;
    name?: null | string;
    type: string;
    sortOrder: number;
};

export type CreateMemberTypePropertyTypeRequestModel = {
    isSensitive: boolean;
    visibility: MemberTypePropertyTypeVisibilityModel;
    id: string;
    container?: null | ReferenceByIdModel;
    sortOrder: number;
    alias: string;
    name: string;
    description?: null | string;
    dataType: ReferenceByIdModel;
    variesByCulture: boolean;
    variesBySegment: boolean;
    validation: PropertyTypeValidationModel;
    appearance: PropertyTypeAppearanceModel;
};

export type CreateMemberTypeRequestModel = {
    compositions: Array<MemberTypeCompositionModel>;
    parent?: null | ReferenceByIdModel;
    id?: null | string;
    alias: string;
    name: string;
    description?: null | string;
    icon: string;
    allowedAsRoot: boolean;
    variesByCulture: boolean;
    variesBySegment: boolean;
    collection?: null | ReferenceByIdModel;
    isElement: boolean;
    allowedInLibrary: boolean;
    properties: Array<CreateMemberTypePropertyTypeRequestModel>;
    containers: Array<CreateMemberTypePropertyTypeContainerRequestModel>;
};

export type CreatePackageRequestModel = {
    id?: null | string;
    name: string;
    contentNodeId?: null | string;
    contentLoadChildNodes: boolean;
    mediaIds: Array<string>;
    mediaLoadChildNodes: boolean;
    documentTypes: Array<string>;
    mediaTypes: Array<string>;
    dataTypes: Array<string>;
    templates: Array<string>;
    partialViews: Array<string>;
    stylesheets: Array<string>;
    scripts: Array<string>;
    languages: Array<string>;
    dictionaryItems: Array<string>;
};

export type CreatePartialViewFolderRequestModel = {
    name: string;
    parent?: null | FileSystemFolderModel;
};

export type CreatePartialViewRequestModel = {
    content: string;
    name: string;
    parent?: null | FileSystemFolderModel;
};

export type CreateScriptFolderRequestModel = {
    name: string;
    parent?: null | FileSystemFolderModel;
};

export type CreateScriptRequestModel = {
    content: string;
    name: string;
    parent?: null | FileSystemFolderModel;
};

export type CreateStylesheetFolderRequestModel = {
    name: string;
    parent?: null | FileSystemFolderModel;
};

export type CreateStylesheetRequestModel = {
    content: string;
    name: string;
    parent?: null | FileSystemFolderModel;
};

export type CreateTemplateRequestModel = {
    id?: null | string;
    name: string;
    alias: string;
    content?: null | string;
};

export type CreateUserClientCredentialsRequestModel = {
    clientId: string;
    clientSecret: string;
};

export type CreateUserDataRequestModel = {
    key?: null | string;
    group: string;
    identifier: string;
    value: string;
};

export type CreateUserGroupRequestModel = {
    id?: null | string;
    name: string;
    alias: string;
    description?: null | string;
    icon?: null | string;
    sections: Array<string>;
    languages: Array<string>;
    hasAccessToAllLanguages: boolean;
    documentStartNode?: null | ReferenceByIdModel;
    documentRootAccess: boolean;
    mediaStartNode?: null | ReferenceByIdModel;
    mediaRootAccess: boolean;
    elementStartNode?: null | ReferenceByIdModel;
    elementRootAccess: boolean;
    fallbackPermissions: Array<string>;
    permissions: Array<IPermissionPresentationModel>;
};

export type CreateUserRequestModel = {
    kind: UserKindModel;
    id?: null | string;
    email: string;
    userName: string;
    name: string;
    userGroupIds: Array<ReferenceByIdModel>;
};

export type CreateWebhookRequestModel = {
    id?: null | string;
    events: Array<string>;
    enabled: boolean;
    name?: null | string;
    description?: null | string;
    url: string;
    contentTypeKeys: Array<string>;
    headers: {
        [key: string]: string;
    };
};

export type CultureAndScheduleRequestModel = {
    culture?: null | string;
    schedule?: null | ScheduleRequestModel;
};

export type CultureReponseModel = {
    name: string;
    englishName: string;
};

export type CurrentUserConfigurationResponseModel = {
    keepUserLoggedIn: boolean;
    passwordConfiguration: PasswordConfigurationResponseModel;
    allowChangePassword: boolean;
    allowTwoFactor: boolean;
};

export type CurrentUserResponseModel = {
    id: string;
    languageIsoCode: null | string;
    documentStartNodeIds: Array<ReferenceByIdModel>;
    hasDocumentRootAccess: boolean;
    mediaStartNodeIds: Array<ReferenceByIdModel>;
    hasMediaRootAccess: boolean;
    elementStartNodeIds: Array<ReferenceByIdModel>;
    hasElementRootAccess: boolean;
    avatarUrls: Array<string>;
    languages: Array<string>;
    hasAccessToAllLanguages: boolean;
    hasAccessToSensitiveData: boolean;
    fallbackPermissions: Array<string>;
    permissions: Array<IPermissionPresentationModel>;
    allowedSections: Array<string>;
    isAdmin: boolean;
    email: string;
    userName: string;
    name: string;
    userGroupIds: Array<ReferenceByIdModel>;
};

export type DatabaseInstallRequestModel = {
    id: string;
    providerName: null | string;
    server?: null | string;
    name?: null | string;
    username?: null | string;
    password?: null | string;
    useIntegratedAuthentication: boolean;
    connectionString?: null | string;
    trustServerCertificate: boolean;
};

export type DatabaseSettingsPresentationModel = {
    id: string;
    sortOrder: number;
    displayName: string;
    defaultDatabaseName: string;
    providerName: string;
    isConfigured: boolean;
    requiresServer: boolean;
    serverPlaceholder: string;
    requiresCredentials: boolean;
    supportsIntegratedAuthentication: boolean;
    supportsTrustServerCertificate: boolean;
    requiresConnectionTest: boolean;
};

export type DataTypeChangeModeModel = 'True' | 'False' | 'FalseWithHelpText';

export type DatatypeConfigurationResponseModel = {
    canBeChanged: DataTypeChangeModeModel;
    documentListViewId: string;
    mediaListViewId: string;
};

export type DataTypeItemResponseModel = {
    editorUiAlias?: null | string;
    editorAlias: string;
    isDeletable: boolean;
    name: string;
    id: string;
    flags: Array<FlagModel>;
};

export type DataTypePropertyPresentationModel = {
    alias: string;
    value?: unknown;
};

export type DataTypeResponseModel = {
    id: string;
    isDeletable: boolean;
    canIgnoreStartNodes: boolean;
    name: string;
    editorAlias: string;
    editorUiAlias: string;
    values: Array<DataTypePropertyPresentationModel>;
};

export type DataTypeSchemaItemResponseModel = {
    id: string;
    valueTypeName?: null | string;
    jsonSchema?: null | JsonObject;
    error?: null | string;
};

export type DataTypeSchemaResponseModel = {
    valueTypeName?: null | string;
    jsonSchema?: null | JsonObject;
};

export type DataTypeTreeItemResponseModel = {
    editorUiAlias?: null | string;
    isDeletable: boolean;
    isFolder: boolean;
    noAccess: boolean;
    name: string;
    id: string;
    parent?: null | ReferenceByIdModel;
    flags: Array<FlagModel>;
    hasChildren: boolean;
};

export type DeleteUserGroupsRequestModel = {
    userGroupIds: Array<ReferenceByIdModel>;
};

export type DeleteUsersRequestModel = {
    userIds: Array<ReferenceByIdModel>;
};

export type DictionaryItemItemResponseModel = {
    name: string;
    id: string;
    flags: Array<FlagModel>;
};

export type DictionaryItemResponseModel = {
    id: string;
    name: string;
    translations: Array<DictionaryItemTranslationModel>;
};

export type DictionaryItemTranslationModel = {
    isoCode: string;
    translation: string;
};

export type DictionaryOverviewResponseModel = {
    name?: null | string;
    id: string;
    parent?: null | ReferenceByIdModel;
    translatedIsoCodes: Array<string>;
};

export type DirectionModel = 'Ascending' | 'Descending';

export type DisableUserRequestModel = {
    userIds: Array<ReferenceByIdModel>;
};

export type DocumentBlueprintItemResponseModel = {
    documentType: DocumentTypeReferenceResponseModel;
    name: string;
    id: string;
    flags: Array<FlagModel>;
};

export type DocumentBlueprintResponseModel = {
    documentType: DocumentTypeReferenceResponseModel;
    id: string;
    flags: Array<FlagModel>;
    values: Array<DocumentValueResponseModel>;
    variants: Array<DocumentVariantResponseModel>;
};

export type DocumentBlueprintTreeItemResponseModel = {
    documentType?: null | DocumentTypeReferenceResponseModel;
    isFolder: boolean;
    noAccess: boolean;
    name: string;
    id: string;
    parent?: null | ReferenceByIdModel;
    flags: Array<FlagModel>;
    hasChildren: boolean;
};

export type DocumentCollectionResponseModel = {
    documentType: DocumentTypeCollectionReferenceResponseModel;
    isTrashed: boolean;
    isProtected: boolean;
    ancestors: Array<ReferenceByIdModel>;
    updater?: null | string;
    creator?: null | string;
    sortOrder: number;
    id: string;
    flags: Array<FlagModel>;
    values: Array<DocumentValueResponseModel>;
    variants: Array<DocumentVariantResponseModel>;
};

export type DocumentConfigurationResponseModel = {
    disableDeleteWhenReferenced: boolean;
    disableUnpublishWhenReferenced: boolean;
    allowEditInvariantFromNonDefault: boolean;
    allowNonExistingSegmentsCreation: boolean;
};

export type DocumentItemResponseModel = {
    isTrashed: boolean;
    isProtected: boolean;
    parent?: null | ReferenceByIdModel;
    hasChildren: boolean;
    documentType: DocumentTypeReferenceResponseModel;
    variants: Array<DocumentVariantItemResponseModel>;
    id: string;
    flags: Array<FlagModel>;
};

export type DocumentNotificationResponseModel = {
    actionId: string;
    alias: string;
    subscribed: boolean;
};

export type DocumentRecycleBinItemResponseModel = {
    documentType: DocumentTypeReferenceResponseModel;
    variants: Array<DocumentVariantItemResponseModel>;
    id: string;
    createDate: string;
    hasChildren: boolean;
    parent?: null | ItemReferenceByIdResponseModel;
};

export type DocumentResponseModel = {
    template?: null | ReferenceByIdModel;
    isTrashed: boolean;
    documentType: DocumentTypeReferenceResponseModel;
    id: string;
    flags: Array<FlagModel>;
    values: Array<DocumentValueResponseModel>;
    variants: Array<DocumentVariantResponseModel>;
};

export type DocumentTreeItemResponseModel = {
    isProtected: boolean;
    ancestors: Array<ReferenceByIdModel>;
    documentType: DocumentTypeReferenceResponseModel;
    variants: Array<DocumentVariantItemResponseModel>;
    noAccess: boolean;
    isTrashed: boolean;
    createDate: string;
    id: string;
    parent?: null | ReferenceByIdModel;
    flags: Array<FlagModel>;
    hasChildren: boolean;
};

export type DocumentTypeAllowedParentsResponseModel = {
    allowedParentIds: Array<ReferenceByIdModel>;
};

export type DocumentTypeBlueprintItemResponseModel = {
    name: string;
    id: string;
    flags: Array<FlagModel>;
};

export type DocumentTypeCleanupModel = {
    preventCleanup: boolean;
    keepAllVersionsNewerThanDays?: null | number;
    keepLatestVersionPerDayForDays?: null | number;
};

export type DocumentTypeCollectionReferenceResponseModel = {
    id: string;
    alias: string;
    icon: string;
    collection?: null | ReferenceByIdModel;
};

export type DocumentTypeCompositionModel = {
    documentType: ReferenceByIdModel;
    compositionType: CompositionTypeModel;
};

export type DocumentTypeCompositionRequestModel = {
    isElement: boolean;
    id?: null | string;
    currentPropertyAliases: Array<string>;
    currentCompositeIds: Array<string>;
};

export type DocumentTypeCompositionResponseModel = {
    id: string;
    name: string;
    icon: string;
};

export type DocumentTypeConfigurationResponseModel = {
    dataTypesCanBeChanged: DataTypeChangeModeModel;
    disableTemplates: boolean;
    useSegments: boolean;
    reservedFieldNames: Array<string>;
};

export type DocumentTypeItemResponseModel = {
    isElement: boolean;
    allowedInLibrary: boolean;
    icon?: null | string;
    description?: null | string;
    name: string;
    id: string;
    flags: Array<FlagModel>;
};

export type DocumentTypePropertyTypeContainerResponseModel = {
    id: string;
    parent?: null | ReferenceByIdModel;
    name?: null | string;
    type: string;
    sortOrder: number;
};

export type DocumentTypePropertyTypeResponseModel = {
    id: string;
    container?: null | ReferenceByIdModel;
    sortOrder: number;
    alias: string;
    name: string;
    description?: null | string;
    dataType: ReferenceByIdModel;
    variesByCulture: boolean;
    variesBySegment: boolean;
    validation: PropertyTypeValidationModel;
    appearance: PropertyTypeAppearanceModel;
};

export type DocumentTypeReferenceResponseModel = {
    id: string;
    icon: string;
    collection?: null | ReferenceByIdModel;
};

export type DocumentTypeResponseModel = {
    allowedTemplates: Array<ReferenceByIdModel>;
    defaultTemplate?: null | ReferenceByIdModel;
    cleanup: DocumentTypeCleanupModel;
    allowedDocumentTypes: Array<DocumentTypeSortModel>;
    compositions: Array<DocumentTypeCompositionModel>;
    id: string;
    alias: string;
    name: string;
    description?: null | string;
    icon: string;
    allowedAsRoot: boolean;
    variesByCulture: boolean;
    variesBySegment: boolean;
    collection?: null | ReferenceByIdModel;
    isElement: boolean;
    allowedInLibrary: boolean;
    properties: Array<DocumentTypePropertyTypeResponseModel>;
    containers: Array<DocumentTypePropertyTypeContainerResponseModel>;
};

export type DocumentTypeSortModel = {
    documentType: ReferenceByIdModel;
    sortOrder: number;
};

export type DocumentTypeTreeItemResponseModel = {
    isElement: boolean;
    icon: string;
    isFolder: boolean;
    noAccess: boolean;
    name: string;
    id: string;
    parent?: null | ReferenceByIdModel;
    flags: Array<FlagModel>;
    hasChildren: boolean;
};

export type DocumentUrlInfoModel = {
    message: null | string;
    provider: string;
    culture: null | string;
    url: null | string;
};

export type DocumentUrlInfoResponseModel = {
    id: string;
    urlInfos: Array<DocumentUrlInfoModel>;
};

export type DocumentValueModel = {
    culture?: null | string;
    segment?: null | string;
    alias: string;
    value?: unknown;
};

export type DocumentValueResponseModel = {
    editorAlias: string;
    culture?: null | string;
    segment?: null | string;
    alias: string;
    value?: unknown;
};

export type DocumentVariantItemResponseModel = {
    id: string;
    flags: Array<FlagModel>;
    state: PublishableVariantStateModel;
    name: string;
    culture?: null | string;
};

export type DocumentVariantRequestModel = {
    culture?: null | string;
    segment?: null | string;
    name: string;
};

export type DocumentVariantResponseModel = {
    id: string;
    flags: Array<FlagModel>;
    state: PublishableVariantStateModel;
    publishDate?: null | string;
    scheduledPublishDate?: null | string;
    scheduledUnpublishDate?: null | string;
    createDate: string;
    updateDate: string;
    culture?: null | string;
    segment?: null | string;
    name: string;
};

export type DocumentVersionItemResponseModel = {
    id: string;
    document: ReferenceByIdModel;
    documentType: ReferenceByIdModel;
    user: ReferenceByIdModel;
    versionDate: string;
    isCurrentPublishedVersion: boolean;
    isCurrentDraftVersion: boolean;
    preventCleanup: boolean;
};

export type DocumentVersionResponseModel = {
    document?: null | ReferenceByIdModel;
    documentType: DocumentTypeReferenceResponseModel;
    id: string;
    flags: Array<FlagModel>;
    values: Array<DocumentValueResponseModel>;
    variants: Array<DocumentVariantResponseModel>;
};

export type DomainPresentationModel = {
    domainName: string;
    isoCode: string;
};

export type DomainsResponseModel = {
    defaultIsoCode?: null | string;
    domains: Array<DomainPresentationModel>;
};

export type DynamicRootContextRequestModel = {
    id?: null | string;
    parent: ReferenceByIdModel;
    culture?: null | string;
    segment?: null | string;
};

export type DynamicRootQueryOriginRequestModel = {
    alias: string;
    id?: null | string;
};

export type DynamicRootQueryRequestModel = {
    origin: DynamicRootQueryOriginRequestModel;
    steps: Array<DynamicRootQueryStepRequestModel>;
};

export type DynamicRootQueryStepRequestModel = {
    alias: string;
    documentTypeIds: Array<string>;
};

export type DynamicRootRequestModel = {
    context: DynamicRootContextRequestModel;
    query: DynamicRootQueryRequestModel;
};

export type DynamicRootResponseModel = {
    roots: Array<string>;
};

export type ElementConfigurationResponseModel = {
    disableDeleteWhenReferenced: boolean;
    disableUnpublishWhenReferenced: boolean;
    allowEditInvariantFromNonDefault: boolean;
    allowNonExistingSegmentsCreation: boolean;
};

export type ElementItemResponseModel = {
    isTrashed: boolean;
    parent?: null | ReferenceByIdModel;
    hasChildren: boolean;
    documentType: DocumentTypeReferenceResponseModel;
    variants: Array<ElementVariantItemResponseModel>;
    id: string;
    flags: Array<FlagModel>;
};

export type ElementRecycleBinItemResponseModel = {
    documentType?: null | DocumentTypeReferenceResponseModel;
    variants: Array<ElementVariantItemResponseModel>;
    isFolder: boolean;
    name: string;
    id: string;
    createDate: string;
    hasChildren: boolean;
    parent?: null | ItemReferenceByIdResponseModel;
};

export type ElementResponseModel = {
    isTrashed: boolean;
    documentType: DocumentTypeReferenceResponseModel;
    id: string;
    flags: Array<FlagModel>;
    values: Array<ElementValueResponseModel>;
    variants: Array<ElementVariantResponseModel>;
};

export type ElementTreeItemResponseModel = {
    createDate: string;
    documentType?: null | DocumentTypeReferenceResponseModel;
    variants: Array<ElementVariantItemResponseModel>;
    isFolder: boolean;
    noAccess: boolean;
    name: string;
    id: string;
    parent?: null | ReferenceByIdModel;
    flags: Array<FlagModel>;
    hasChildren: boolean;
};

export type ElementValueModel = {
    culture?: null | string;
    segment?: null | string;
    alias: string;
    value?: unknown;
};

export type ElementValueResponseModel = {
    editorAlias: string;
    culture?: null | string;
    segment?: null | string;
    alias: string;
    value?: unknown;
};

export type ElementVariantItemResponseModel = {
    id: string;
    flags: Array<FlagModel>;
    state: PublishableVariantStateModel;
    name: string;
    culture?: null | string;
};

export type ElementVariantRequestModel = {
    culture?: null | string;
    segment?: null | string;
    name: string;
};

export type ElementVariantResponseModel = {
    id: string;
    flags: Array<FlagModel>;
    state: PublishableVariantStateModel;
    publishDate?: null | string;
    scheduledPublishDate?: null | string;
    scheduledUnpublishDate?: null | string;
    createDate: string;
    updateDate: string;
    culture?: null | string;
    segment?: null | string;
    name: string;
};

export type ElementVersionItemResponseModel = {
    id: string;
    element: ReferenceByIdModel;
    documentType: ReferenceByIdModel;
    user: ReferenceByIdModel;
    versionDate: string;
    isCurrentPublishedVersion: boolean;
    isCurrentDraftVersion: boolean;
    preventCleanup: boolean;
};

export type ElementVersionResponseModel = {
    element?: null | ReferenceByIdModel;
    documentType: DocumentTypeReferenceResponseModel;
    id: string;
    flags: Array<FlagModel>;
    values: Array<ElementValueResponseModel>;
    variants: Array<ElementVariantResponseModel>;
};

export type EnableTwoFactorRequestModel = {
    code: string;
    secret: string;
};

export type EnableUserRequestModel = {
    userIds: Array<ReferenceByIdModel>;
};

export type EntityImportAnalysisResponseModel = {
    entityType: string;
    alias?: null | string;
    key?: null | string;
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type FetchResponseModelDataTypeSchemaItemResponseModel = {
    total: number;
    items: Array<DataTypeSchemaItemResponseModel>;
};

export type FieldPresentationModel = {
    name: string;
    values: Array<string>;
};

export type FileSystemFolderModel = {
    path: string;
};

export type FileSystemTreeItemPresentationModel = {
    name: string;
    path: string;
    parent?: null | FileSystemFolderModel;
    isFolder: boolean;
    hasChildren: boolean;
};

export type FlagModel = {
    alias: string;
};

export type FolderItemResponseModel = {
    name: string;
    id: string;
    flags: Array<FlagModel>;
};

export type FolderResponseModel = {
    id: string;
    isTrashed: boolean;
    name: string;
};

export type HealthCheckActionRequestModel = {
    healthCheck: ReferenceByIdModel;
    alias?: null | string;
    name?: null | string;
    description?: null | string;
    valueRequired: boolean;
    providedValue?: null | string;
    providedValueValidation?: null | string;
    providedValueValidationRegex?: null | string;
    actionParameters?: null | {
        [key: string]: unknown;
    };
};

export type HealthCheckGroupPresentationModel = {
    checks: Array<HealthCheckModel>;
    name: string;
};

export type HealthCheckGroupResponseModel = {
    name: string;
};

export type HealthCheckGroupWithResultResponseModel = {
    checks: Array<HealthCheckWithResultPresentationModel>;
};

export type HealthCheckModel = {
    name: string;
    description?: null | string;
    id: string;
};

export type HealthCheckResultResponseModel = {
    message: string;
    resultType: StatusResultTypeModel;
    actions?: null | Array<HealthCheckActionRequestModel>;
    readMoreLink?: null | string;
};

export type HealthCheckWithResultPresentationModel = {
    results?: null | Array<HealthCheckResultResponseModel>;
    id: string;
};

export type HealthStatusModel = 'Healthy' | 'Unhealthy' | 'Rebuilding' | 'Corrupt';

export type HealthStatusResponseModel = {
    status: HealthStatusModel;
    message?: null | string;
};

export type HelpPageResponseModel = {
    name?: null | string;
    description?: null | string;
    url?: null | string;
    type?: null | string;
};

export type ImageCropModeModel = 'Crop' | 'Max' | 'Stretch' | 'Pad' | 'BoxPad' | 'Min';

export type ImportDictionaryRequestModel = {
    temporaryFile: ReferenceByIdModel;
    parent?: null | ReferenceByIdModel;
};

export type ImportDocumentTypeRequestModel = {
    file: ReferenceByIdModel;
};

export type ImportMediaTypeRequestModel = {
    file: ReferenceByIdModel;
};

export type ImportMemberTypeRequestModel = {
    file: ReferenceByIdModel;
};

export type IndexResponseModel = {
    name: string;
    healthStatus: HealthStatusResponseModel;
    canRebuild: boolean;
    searcherName: string;
    documentCount: number;
    fieldCount: number;
    providerProperties?: null | {
        [key: string]: unknown;
    };
    uniqueKeyFieldName?: null | string;
};

export type InstallRequestModel = {
    user: UserInstallRequestModel;
    database: DatabaseInstallRequestModel;
    telemetryLevel: TelemetryLevelModel;
};

export type InstallSettingsResponseModel = {
    user: UserSettingsPresentationModel;
    databases: Array<DatabaseSettingsPresentationModel>;
};

export type InviteUserRequestModel = {
    message?: null | string;
    id?: null | string;
    email: string;
    userName: string;
    name: string;
    userGroupIds: Array<ReferenceByIdModel>;
};

export type IPermissionPresentationModel = ({
    $type?: 'DocumentPermissionPresentationModel';
} & IPermissionPresentationModelDocumentPermissionPresentationModel) | ({
    $type?: 'DocumentPropertyValuePermissionPresentationModel';
} & IPermissionPresentationModelDocumentPropertyValuePermissionPresentationModel) | ({
    $type?: 'ElementPermissionPresentationModel';
} & IPermissionPresentationModelElementPermissionPresentationModel) | ({
    $type?: 'UnknownTypePermissionPresentationModel';
} & IPermissionPresentationModelUnknownTypePermissionPresentationModel);

export type IPermissionPresentationModelDocumentPermissionPresentationModel = {
    $type: 'DocumentPermissionPresentationModel';
    document: ReferenceByIdModel;
    verbs: Array<string>;
};

export type IPermissionPresentationModelDocumentPropertyValuePermissionPresentationModel = {
    $type: 'DocumentPropertyValuePermissionPresentationModel';
    documentType: ReferenceByIdModel;
    propertyType: ReferenceByIdModel;
    verbs: Array<string>;
};

export type IPermissionPresentationModelElementPermissionPresentationModel = {
    $type: 'ElementPermissionPresentationModel';
    element: ReferenceByIdModel;
    verbs: Array<string>;
};

export type IPermissionPresentationModelUnknownTypePermissionPresentationModel = {
    $type: 'UnknownTypePermissionPresentationModel';
    verbs: Array<string>;
    context: string;
};

export type IReferenceResponseModel = ({
    $type?: 'DefaultReferenceResponseModel';
} & IReferenceResponseModelDefaultReferenceResponseModel) | ({
    $type?: 'DocumentReferenceResponseModel';
} & IReferenceResponseModelDocumentReferenceResponseModel) | ({
    $type?: 'DocumentTypePropertyTypeReferenceResponseModel';
} & IReferenceResponseModelDocumentTypePropertyTypeReferenceResponseModel) | ({
    $type?: 'ElementContainerReferenceResponseModel';
} & IReferenceResponseModelElementContainerReferenceResponseModel) | ({
    $type?: 'ElementReferenceResponseModel';
} & IReferenceResponseModelElementReferenceResponseModel) | ({
    $type?: 'MediaReferenceResponseModel';
} & IReferenceResponseModelMediaReferenceResponseModel) | ({
    $type?: 'MediaTypePropertyTypeReferenceResponseModel';
} & IReferenceResponseModelMediaTypePropertyTypeReferenceResponseModel) | ({
    $type?: 'MemberReferenceResponseModel';
} & IReferenceResponseModelMemberReferenceResponseModel) | ({
    $type?: 'MemberTypePropertyTypeReferenceResponseModel';
} & IReferenceResponseModelMemberTypePropertyTypeReferenceResponseModel);

export type IReferenceResponseModelDefaultReferenceResponseModel = {
    $type: 'DefaultReferenceResponseModel';
    type?: null | string;
    icon?: null | string;
    id: string;
    name?: null | string;
};

export type IReferenceResponseModelDocumentReferenceResponseModel = {
    $type: 'DocumentReferenceResponseModel';
    published?: null | boolean;
    documentType: TrackedReferenceDocumentTypeModel;
    variants: Array<DocumentVariantItemResponseModel>;
    id: string;
    name?: null | string;
};

export type IReferenceResponseModelDocumentTypePropertyTypeReferenceResponseModel = {
    $type: 'DocumentTypePropertyTypeReferenceResponseModel';
    documentType: TrackedReferenceDocumentTypeModel;
    alias?: null | string;
    id: string;
    name?: null | string;
};

export type IReferenceResponseModelElementContainerReferenceResponseModel = {
    $type: 'ElementContainerReferenceResponseModel';
    id: string;
    name?: null | string;
};

export type IReferenceResponseModelElementReferenceResponseModel = {
    $type: 'ElementReferenceResponseModel';
    published?: null | boolean;
    documentType: TrackedReferenceDocumentTypeModel;
    variants: Array<ElementVariantItemResponseModel>;
    id: string;
    name?: null | string;
};

export type IReferenceResponseModelMediaReferenceResponseModel = {
    $type: 'MediaReferenceResponseModel';
    mediaType: TrackedReferenceMediaTypeModel;
    id: string;
    name?: null | string;
};

export type IReferenceResponseModelMediaTypePropertyTypeReferenceResponseModel = {
    $type: 'MediaTypePropertyTypeReferenceResponseModel';
    mediaType: TrackedReferenceMediaTypeModel;
    alias?: null | string;
    id: string;
    name?: null | string;
};

export type IReferenceResponseModelMemberReferenceResponseModel = {
    $type: 'MemberReferenceResponseModel';
    memberType: TrackedReferenceMemberTypeModel;
    id: string;
    name?: null | string;
};

export type IReferenceResponseModelMemberTypePropertyTypeReferenceResponseModel = {
    $type: 'MemberTypePropertyTypeReferenceResponseModel';
    memberType: TrackedReferenceMemberTypeModel;
    alias?: null | string;
    id: string;
    name?: null | string;
};

export type ISetupTwoFactorModel = {
    $type?: 'NoopSetupTwoFactorModel';
} & ISetupTwoFactorModelNoopSetupTwoFactorModel;

export type ISetupTwoFactorModelNoopSetupTwoFactorModel = {
    $type: 'NoopSetupTwoFactorModel';
};

export type ItemAncestorsResponseModelDocumentItemResponseModel = {
    id: string;
    ancestors: Array<DocumentItemResponseModel>;
};

export type ItemAncestorsResponseModelMediaItemResponseModel = {
    id: string;
    ancestors: Array<MediaItemResponseModel>;
};

export type ItemAncestorsResponseModelMemberItemResponseModel = {
    id: string;
    ancestors: Array<MemberItemResponseModel>;
};

export type ItemAncestorsResponseModelNamedItemResponseModel = {
    id: string;
    ancestors: Array<NamedItemResponseModel>;
};

export type ItemAncestorsResponseModelTemplateItemResponseModel = {
    id: string;
    ancestors: Array<TemplateItemResponseModel>;
};

export type ItemReferenceByIdResponseModel = {
    id: string;
};

export type ItemSortingRequestModel = {
    id: string;
    sortOrder: number;
};

export type JsonObject = {
    [key: string]: unknown;
};

export type LanguageItemResponseModel = {
    name: string;
    isoCode: string;
};

export type LanguageResponseModel = {
    isoCode: string;
    name: string;
    isDefault: boolean;
    isMandatory: boolean;
    fallbackIsoCode?: null | string;
};

export type LoggerResponseModel = {
    name: string;
    level: LogLevelModel;
};

export type LogLevelCountsReponseModel = {
    information: number;
    debug: number;
    warning: number;
    error: number;
    fatal: number;
};

export type LogLevelModel = 'Verbose' | 'Debug' | 'Information' | 'Warning' | 'Error' | 'Fatal';

export type LogMessagePropertyPresentationModel = {
    name: string;
    value?: null | string;
};

export type LogMessageResponseModel = {
    timestamp: string;
    level: LogLevelModel;
    messageTemplate?: null | string;
    renderedMessage?: null | string;
    properties: Array<LogMessagePropertyPresentationModel>;
    exception?: null | string;
};

export type LogTemplateResponseModel = {
    messageTemplate?: null | string;
    count: number;
};

export type ManifestResponseModel = {
    name: string;
    id?: null | string;
    version?: null | string;
    extensions: Array<unknown>;
};

export type MediaCollectionResponseModel = {
    mediaType: MediaTypeCollectionReferenceResponseModel;
    creator?: null | string;
    sortOrder: number;
    id: string;
    flags: Array<FlagModel>;
    values: Array<MediaValueResponseModel>;
    variants: Array<MediaVariantResponseModel>;
};

export type MediaConfigurationResponseModel = {
    disableDeleteWhenReferenced: boolean;
    disableUnpublishWhenReferenced: boolean;
};

export type MediaItemResponseModel = {
    isTrashed: boolean;
    parent?: null | ReferenceByIdModel;
    hasChildren: boolean;
    mediaType: MediaTypeReferenceResponseModel;
    variants: Array<VariantItemResponseModel>;
    id: string;
    flags: Array<FlagModel>;
};

export type MediaRecycleBinItemResponseModel = {
    mediaType: MediaTypeReferenceResponseModel;
    variants: Array<VariantItemResponseModel>;
    id: string;
    createDate: string;
    hasChildren: boolean;
    parent?: null | ItemReferenceByIdResponseModel;
};

export type MediaResponseModel = {
    isTrashed: boolean;
    mediaType: MediaTypeReferenceResponseModel;
    id: string;
    flags: Array<FlagModel>;
    values: Array<MediaValueResponseModel>;
    variants: Array<MediaVariantResponseModel>;
};

export type MediaTreeItemResponseModel = {
    mediaType: MediaTypeReferenceResponseModel;
    variants: Array<VariantItemResponseModel>;
    noAccess: boolean;
    isTrashed: boolean;
    createDate: string;
    id: string;
    parent?: null | ReferenceByIdModel;
    flags: Array<FlagModel>;
    hasChildren: boolean;
};

export type MediaTypeAllowedParentsResponseModel = {
    allowedParentIds: Array<ReferenceByIdModel>;
};

export type MediaTypeCollectionReferenceResponseModel = {
    id: string;
    alias: string;
    icon: string;
    collection?: null | ReferenceByIdModel;
};

export type MediaTypeCompositionModel = {
    mediaType: ReferenceByIdModel;
    compositionType: CompositionTypeModel;
};

export type MediaTypeCompositionRequestModel = {
    id?: null | string;
    currentPropertyAliases: Array<string>;
    currentCompositeIds: Array<string>;
};

export type MediaTypeCompositionResponseModel = {
    id: string;
    name: string;
    icon: string;
};

export type MediaTypeConfigurationResponseModel = {
    reservedFieldNames: Array<string>;
};

export type MediaTypeItemResponseModel = {
    icon?: null | string;
    name: string;
    id: string;
    flags: Array<FlagModel>;
};

export type MediaTypePropertyTypeContainerResponseModel = {
    id: string;
    parent?: null | ReferenceByIdModel;
    name?: null | string;
    type: string;
    sortOrder: number;
};

export type MediaTypePropertyTypeResponseModel = {
    id: string;
    container?: null | ReferenceByIdModel;
    sortOrder: number;
    alias: string;
    name: string;
    description?: null | string;
    dataType: ReferenceByIdModel;
    variesByCulture: boolean;
    variesBySegment: boolean;
    validation: PropertyTypeValidationModel;
    appearance: PropertyTypeAppearanceModel;
};

export type MediaTypeReferenceResponseModel = {
    id: string;
    icon: string;
    collection?: null | ReferenceByIdModel;
};

export type MediaTypeResponseModel = {
    allowedMediaTypes: Array<MediaTypeSortModel>;
    compositions: Array<MediaTypeCompositionModel>;
    isDeletable: boolean;
    aliasCanBeChanged: boolean;
    id: string;
    alias: string;
    name: string;
    description?: null | string;
    icon: string;
    allowedAsRoot: boolean;
    variesByCulture: boolean;
    variesBySegment: boolean;
    collection?: null | ReferenceByIdModel;
    isElement: boolean;
    allowedInLibrary: boolean;
    properties: Array<MediaTypePropertyTypeResponseModel>;
    containers: Array<MediaTypePropertyTypeContainerResponseModel>;
};

export type MediaTypeSortModel = {
    mediaType: ReferenceByIdModel;
    sortOrder: number;
};

export type MediaTypeTreeItemResponseModel = {
    icon: string;
    isDeletable: boolean;
    isFolder: boolean;
    noAccess: boolean;
    name: string;
    id: string;
    parent?: null | ReferenceByIdModel;
    flags: Array<FlagModel>;
    hasChildren: boolean;
};

export type MediaUrlInfoModel = {
    culture: null | string;
    url: null | string;
};

export type MediaUrlInfoResponseModel = {
    id: string;
    urlInfos: Array<MediaUrlInfoModel>;
};

export type MediaValueModel = {
    culture?: null | string;
    segment?: null | string;
    alias: string;
    value?: unknown;
};

export type MediaValueResponseModel = {
    editorAlias: string;
    culture?: null | string;
    segment?: null | string;
    alias: string;
    value?: unknown;
};

export type MediaVariantRequestModel = {
    culture?: null | string;
    segment?: null | string;
    name: string;
};

export type MediaVariantResponseModel = {
    createDate: string;
    updateDate: string;
    culture?: null | string;
    segment?: null | string;
    name: string;
};

export type MemberGroupItemResponseModel = {
    name: string;
    id: string;
    flags: Array<FlagModel>;
};

export type MemberGroupResponseModel = {
    id: string;
    name: string;
};

export type MemberItemResponseModel = {
    memberType: MemberTypeReferenceResponseModel;
    variants: Array<VariantItemResponseModel>;
    kind: MemberKindModel;
    id: string;
    flags: Array<FlagModel>;
};

export type MemberKindModel = 'Default' | 'Api' | 'ExternalOnly';

export type MemberResponseModel = {
    email: string;
    username: string;
    memberType: MemberTypeReferenceResponseModel;
    isApproved: boolean;
    isLockedOut: boolean;
    isTwoFactorEnabled: boolean;
    failedPasswordAttempts: number;
    lastLoginDate?: null | string;
    lastLockoutDate?: null | string;
    lastPasswordChangeDate?: null | string;
    groups: Array<string>;
    kind: MemberKindModel;
    profileData?: null | string;
    id: string;
    flags: Array<FlagModel>;
    values: Array<MemberValueResponseModel>;
    variants: Array<MemberVariantResponseModel>;
};

export type MemberTypeCompositionModel = {
    memberType: ReferenceByIdModel;
    compositionType: CompositionTypeModel;
};

export type MemberTypeCompositionRequestModel = {
    id?: null | string;
    currentPropertyAliases: Array<string>;
    currentCompositeIds: Array<string>;
};

export type MemberTypeCompositionResponseModel = {
    id: string;
    name: string;
    icon: string;
};

export type MemberTypeConfigurationResponseModel = {
    reservedFieldNames: Array<string>;
};

export type MemberTypeItemResponseModel = {
    icon?: null | string;
    name: string;
    id: string;
    flags: Array<FlagModel>;
};

export type MemberTypePropertyTypeContainerResponseModel = {
    id: string;
    parent?: null | ReferenceByIdModel;
    name?: null | string;
    type: string;
    sortOrder: number;
};

export type MemberTypePropertyTypeResponseModel = {
    isSensitive: boolean;
    visibility: MemberTypePropertyTypeVisibilityModel;
    id: string;
    container?: null | ReferenceByIdModel;
    sortOrder: number;
    alias: string;
    name: string;
    description?: null | string;
    dataType: ReferenceByIdModel;
    variesByCulture: boolean;
    variesBySegment: boolean;
    validation: PropertyTypeValidationModel;
    appearance: PropertyTypeAppearanceModel;
};

export type MemberTypePropertyTypeVisibilityModel = {
    memberCanView: boolean;
    memberCanEdit: boolean;
};

export type MemberTypeReferenceResponseModel = {
    id: string;
    icon: string;
    collection?: null | ReferenceByIdModel;
};

export type MemberTypeResponseModel = {
    compositions: Array<MemberTypeCompositionModel>;
    id: string;
    alias: string;
    name: string;
    description?: null | string;
    icon: string;
    allowedAsRoot: boolean;
    variesByCulture: boolean;
    variesBySegment: boolean;
    collection?: null | ReferenceByIdModel;
    isElement: boolean;
    allowedInLibrary: boolean;
    properties: Array<MemberTypePropertyTypeResponseModel>;
    containers: Array<MemberTypePropertyTypeContainerResponseModel>;
};

export type MemberTypeTreeItemResponseModel = {
    icon: string;
    isFolder: boolean;
    noAccess: boolean;
    name: string;
    id: string;
    parent?: null | ReferenceByIdModel;
    flags: Array<FlagModel>;
    hasChildren: boolean;
};

export type MemberValueModel = {
    culture?: null | string;
    segment?: null | string;
    alias: string;
    value?: unknown;
};

export type MemberValueResponseModel = {
    editorAlias: string;
    culture?: null | string;
    segment?: null | string;
    alias: string;
    value?: unknown;
};

export type MemberVariantRequestModel = {
    culture?: null | string;
    segment?: null | string;
    name: string;
};

export type MemberVariantResponseModel = {
    createDate: string;
    updateDate: string;
    culture?: null | string;
    segment?: null | string;
    name: string;
};

export type ModelsBuilderResponseModel = {
    mode: string;
    canGenerate: boolean;
    outOfDateModels: boolean;
    lastError?: null | string;
    version?: null | string;
    modelsNamespace?: null | string;
    trackingOutOfDateModels: boolean;
};

export type MoveDataTypeRequestModel = {
    target?: null | ReferenceByIdModel;
};

export type MoveDictionaryRequestModel = {
    target?: null | ReferenceByIdModel;
};

export type MoveDocumentBlueprintRequestModel = {
    target?: null | ReferenceByIdModel;
};

export type MoveDocumentRequestModel = {
    target?: null | ReferenceByIdModel;
};

export type MoveDocumentTypeRequestModel = {
    target?: null | ReferenceByIdModel;
};

export type MoveElementRequestModel = {
    target?: null | ReferenceByIdModel;
};

export type MoveFolderRequestModel = {
    target?: null | ReferenceByIdModel;
};

export type MoveMediaRequestModel = {
    target?: null | ReferenceByIdModel;
};

export type MoveMediaTypeRequestModel = {
    target?: null | ReferenceByIdModel;
};

export type MoveMemberTypeRequestModel = {
    target?: null | ReferenceByIdModel;
};

export type NamedEntityTreeItemResponseModel = {
    name: string;
    id: string;
    parent?: null | ReferenceByIdModel;
    flags: Array<FlagModel>;
    hasChildren: boolean;
};

export type NamedItemResponseModel = {
    name: string;
    id: string;
    flags: Array<FlagModel>;
};

export type NewsDashboardItemResponseModel = {
    priority: string;
    header: string;
    body?: null | string;
    buttonText?: null | string;
    imageUrl?: null | string;
    imageAltText?: null | string;
    url?: null | string;
};

export type NewsDashboardResponseModel = {
    items: Array<NewsDashboardItemResponseModel>;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type ObjectTypeResponseModel = {
    name?: null | string;
    id: string;
};

export type OEmbedResponseModel = {
    markup: string;
};

export type OperatorModel = 'Equals' | 'NotEquals' | 'Contains' | 'NotContains' | 'LessThan' | 'LessThanEqualTo' | 'GreaterThan' | 'GreaterThanEqualTo';

export type OutOfDateStatusResponseModel = {
    status: OutOfDateTypeModel;
};

export type OutOfDateTypeModel = 'OutOfDate' | 'Current' | 'Unknown';

export type PackageConfigurationResponseModel = {
    marketplaceUrl: string;
};

export type PackageDefinitionResponseModel = {
    id: string;
    packagePath: string;
    name: string;
    contentNodeId?: null | string;
    contentLoadChildNodes: boolean;
    mediaIds: Array<string>;
    mediaLoadChildNodes: boolean;
    documentTypes: Array<string>;
    mediaTypes: Array<string>;
    dataTypes: Array<string>;
    templates: Array<string>;
    partialViews: Array<string>;
    stylesheets: Array<string>;
    scripts: Array<string>;
    languages: Array<string>;
    dictionaryItems: Array<string>;
};

export type PackageMigrationStatusResponseModel = {
    packageName: string;
    hasPendingMigrations: boolean;
};

export type PagedAllowedDocumentTypeModel = {
    total: number;
    items: Array<AllowedDocumentTypeModel>;
};

export type PagedAllowedMediaTypeModel = {
    total: number;
    items: Array<AllowedMediaTypeModel>;
};

export type PagedAllowedMemberTypeModel = {
    total: number;
    items: Array<AllowedMemberTypeModel>;
};

export type PagedAuditLogResponseModel = {
    total: number;
    items: Array<AuditLogResponseModel>;
};

export type PagedCultureReponseModel = {
    total: number;
    items: Array<CultureReponseModel>;
};

export type PagedDataTypeItemResponseModel = {
    total: number;
    items: Array<DataTypeItemResponseModel>;
};

export type PagedDataTypeTreeItemResponseModel = {
    total: number;
    items: Array<DataTypeTreeItemResponseModel>;
};

export type PagedDictionaryOverviewResponseModel = {
    total: number;
    items: Array<DictionaryOverviewResponseModel>;
};

export type PagedDocumentBlueprintTreeItemResponseModel = {
    total: number;
    items: Array<DocumentBlueprintTreeItemResponseModel>;
};

export type PagedDocumentCollectionResponseModel = {
    total: number;
    items: Array<DocumentCollectionResponseModel>;
};

export type PagedDocumentRecycleBinItemResponseModel = {
    total: number;
    items: Array<DocumentRecycleBinItemResponseModel>;
};

export type PagedDocumentTreeItemResponseModel = {
    total: number;
    items: Array<DocumentTreeItemResponseModel>;
};

export type PagedDocumentTypeBlueprintItemResponseModel = {
    total: number;
    items: Array<DocumentTypeBlueprintItemResponseModel>;
};

export type PagedDocumentTypeTreeItemResponseModel = {
    total: number;
    items: Array<DocumentTypeTreeItemResponseModel>;
};

export type PagedDocumentVersionItemResponseModel = {
    total: number;
    items: Array<DocumentVersionItemResponseModel>;
};

export type PagedElementRecycleBinItemResponseModel = {
    total: number;
    items: Array<ElementRecycleBinItemResponseModel>;
};

export type PagedElementTreeItemResponseModel = {
    total: number;
    items: Array<ElementTreeItemResponseModel>;
};

export type PagedElementVersionItemResponseModel = {
    total: number;
    items: Array<ElementVersionItemResponseModel>;
};

export type PagedFileSystemTreeItemPresentationModel = {
    total: number;
    items: Array<FileSystemTreeItemPresentationModel>;
};

export type PagedHealthCheckGroupResponseModel = {
    total: number;
    items: Array<HealthCheckGroupResponseModel>;
};

export type PagedHelpPageResponseModel = {
    total: number;
    items: Array<HelpPageResponseModel>;
};

export type PagedIndexResponseModel = {
    total: number;
    items: Array<IndexResponseModel>;
};

export type PagedIReferenceResponseModel = {
    total: number;
    items: Array<IReferenceResponseModel>;
};

export type PagedLanguageResponseModel = {
    total: number;
    items: Array<LanguageResponseModel>;
};

export type PagedLoggerResponseModel = {
    total: number;
    items: Array<LoggerResponseModel>;
};

export type PagedLogMessageResponseModel = {
    total: number;
    items: Array<LogMessageResponseModel>;
};

export type PagedLogTemplateResponseModel = {
    total: number;
    items: Array<LogTemplateResponseModel>;
};

export type PagedMediaCollectionResponseModel = {
    total: number;
    items: Array<MediaCollectionResponseModel>;
};

export type PagedMediaRecycleBinItemResponseModel = {
    total: number;
    items: Array<MediaRecycleBinItemResponseModel>;
};

export type PagedMediaTreeItemResponseModel = {
    total: number;
    items: Array<MediaTreeItemResponseModel>;
};

export type PagedMediaTypeTreeItemResponseModel = {
    total: number;
    items: Array<MediaTypeTreeItemResponseModel>;
};

export type PagedMemberGroupResponseModel = {
    total: number;
    items: Array<MemberGroupResponseModel>;
};

export type PagedMemberResponseModel = {
    total: number;
    items: Array<MemberResponseModel>;
};

export type PagedMemberTypeTreeItemResponseModel = {
    total: number;
    items: Array<MemberTypeTreeItemResponseModel>;
};

export type PagedModelAllowedMediaTypeItemResponseModel = {
    items: Array<AllowedMediaTypeItemResponseModel>;
    total: number;
};

export type PagedModelDataTypeItemResponseModel = {
    items: Array<DataTypeItemResponseModel>;
    total: number;
};

export type PagedModelDocumentItemResponseModel = {
    items: Array<DocumentItemResponseModel>;
    total: number;
};

export type PagedModelDocumentTypeItemResponseModel = {
    items: Array<DocumentTypeItemResponseModel>;
    total: number;
};

export type PagedModelElementItemResponseModel = {
    items: Array<ElementItemResponseModel>;
    total: number;
};

export type PagedModelMediaItemResponseModel = {
    items: Array<MediaItemResponseModel>;
    total: number;
};

export type PagedModelMediaTypeItemResponseModel = {
    items: Array<MediaTypeItemResponseModel>;
    total: number;
};

export type PagedModelMemberItemResponseModel = {
    items: Array<MemberItemResponseModel>;
    total: number;
};

export type PagedModelMemberTypeItemResponseModel = {
    items: Array<MemberTypeItemResponseModel>;
    total: number;
};

export type PagedModelTemplateItemResponseModel = {
    items: Array<TemplateItemResponseModel>;
    total: number;
};

export type PagedNamedEntityTreeItemResponseModel = {
    total: number;
    items: Array<NamedEntityTreeItemResponseModel>;
};

export type PagedObjectTypeResponseModel = {
    total: number;
    items: Array<ObjectTypeResponseModel>;
};

export type PagedPackageDefinitionResponseModel = {
    total: number;
    items: Array<PackageDefinitionResponseModel>;
};

export type PagedPackageMigrationStatusResponseModel = {
    total: number;
    items: Array<PackageMigrationStatusResponseModel>;
};

export type PagedPartialViewSnippetItemResponseModel = {
    total: number;
    items: Array<PartialViewSnippetItemResponseModel>;
};

export type PagedProblemDetailsModel = {
    total: number;
    items: Array<ProblemDetails>;
};

export type PagedRedirectUrlResponseModel = {
    total: number;
    items: Array<RedirectUrlResponseModel>;
};

export type PagedReferenceByIdModel = {
    total: number;
    items: Array<ReferenceByIdModel>;
};

export type PagedRelationResponseModel = {
    total: number;
    items: Array<RelationResponseModel>;
};

export type PagedRelationTypeResponseModel = {
    total: number;
    items: Array<RelationTypeResponseModel>;
};

export type PagedSavedLogSearchResponseModel = {
    total: number;
    items: Array<SavedLogSearchResponseModel>;
};

export type PagedSearcherResponseModel = {
    total: number;
    items: Array<SearcherResponseModel>;
};

export type PagedSearchResultResponseModel = {
    total: number;
    items: Array<SearchResultResponseModel>;
};

export type PagedSegmentResponseModel = {
    total: number;
    items: Array<SegmentResponseModel>;
};

export type PagedTagResponseModel = {
    total: number;
    items: Array<TagResponseModel>;
};

export type PagedTelemetryResponseModel = {
    total: number;
    items: Array<TelemetryResponseModel>;
};

export type PagedUserDataResponseModel = {
    total: number;
    items: Array<UserDataResponseModel>;
};

export type PagedUserGroupResponseModel = {
    total: number;
    items: Array<UserGroupResponseModel>;
};

export type PagedUserResponseModel = {
    total: number;
    items: Array<UserResponseModel>;
};

export type PagedWebhookEventModel = {
    total: number;
    items: Array<WebhookEventModel>;
};

export type PagedWebhookLogResponseModel = {
    total: number;
    items: Array<WebhookLogResponseModel>;
};

export type PagedWebhookResponseModel = {
    total: number;
    items: Array<WebhookResponseModel>;
};

export type PartialViewFolderResponseModel = {
    name: string;
    parent?: null | FileSystemFolderModel;
    path: string;
};

export type PartialViewItemResponseModel = {
    isFolder: boolean;
    name: string;
    parent?: null | FileSystemFolderModel;
    path: string;
};

export type PartialViewResponseModel = {
    content: string;
    name: string;
    parent?: null | FileSystemFolderModel;
    path: string;
};

export type PartialViewSnippetItemResponseModel = {
    id: string;
    name: string;
};

export type PartialViewSnippetResponseModel = {
    content: string;
    id: string;
    name: string;
};

export type PasswordConfigurationResponseModel = {
    minimumPasswordLength: number;
    requireNonLetterOrDigit: boolean;
    requireDigit: boolean;
    requireLowercase: boolean;
    requireUppercase: boolean;
};

export type PatchDocumentRequestModel = {
    operations: Array<PatchOperationRequestModel>;
};

export type PatchOperationRequestModel = {
    op: string;
    path: string;
    value?: unknown;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number;
    detail?: null | string;
    instance?: null | string;
};

export type ProblemDetailsBuilderModel = {
    [key: string]: unknown;
};

export type ProfilingStatusRequestModel = {
    enabled: boolean;
};

export type ProfilingStatusResponseModel = {
    enabled: boolean;
};

export type PropertyTypeAppearanceModel = {
    labelOnTop: boolean;
};

export type PropertyTypeValidationModel = {
    mandatory: boolean;
    mandatoryMessage?: null | string;
    regEx?: null | string;
    regExMessage?: null | string;
};

export type PublicAccessRequestModel = {
    memberUserNames: Array<string>;
    memberGroupNames: Array<string>;
    loginDocument: ReferenceByIdModel;
    errorDocument: ReferenceByIdModel;
};

export type PublicAccessResponseModel = {
    members: Array<MemberItemResponseModel>;
    groups: Array<MemberGroupItemResponseModel>;
    isProtectedByAncestor: boolean;
    loginDocument: ReferenceByIdModel;
    errorDocument: ReferenceByIdModel;
};

export type PublishableVariantStateModel = 'NotCreated' | 'Draft' | 'Published' | 'PublishedPendingChanges' | 'Trashed';

export type PublishDocumentRequestModel = {
    publishSchedules: Array<CultureAndScheduleRequestModel>;
};

export type PublishDocumentWithDescendantsRequestModel = {
    includeUnpublishedDescendants: boolean;
    cultures: Array<string>;
};

export type PublishedDocumentResponseModel = {
    template?: null | ReferenceByIdModel;
    isTrashed: boolean;
    documentType: DocumentTypeReferenceResponseModel;
    id: string;
    flags: Array<FlagModel>;
    values: Array<DocumentValueResponseModel>;
    variants: Array<DocumentVariantResponseModel>;
};

export type PublishElementRequestModel = {
    publishSchedules: Array<CultureAndScheduleRequestModel>;
};

export type PublishWithDescendantsResultModel = {
    taskId: string;
    isComplete: boolean;
};

export type RebuildStatusModel = {
    isRebuilding: boolean;
};

export type RedirectStatusModel = 'Enabled' | 'Disabled';

export type RedirectUrlResponseModel = {
    id: string;
    originalUrl: string;
    destinationUrl: string;
    created: string;
    document: ReferenceByIdModel;
    culture?: null | string;
};

export type RedirectUrlStatusResponseModel = {
    status: RedirectStatusModel;
    userIsAdmin: boolean;
};

export type ReferenceByIdModel = {
    id: string;
};

export type RelationReferenceModel = {
    id: string;
    name?: null | string;
};

export type RelationResponseModel = {
    id: string;
    relationType: ReferenceByIdModel;
    parent: RelationReferenceModel;
    child: RelationReferenceModel;
    createDate: string;
    comment?: null | string;
};

export type RelationTypeItemResponseModel = {
    isDeletable: boolean;
    name: string;
    id: string;
    flags: Array<FlagModel>;
};

export type RelationTypeResponseModel = {
    id: string;
    alias?: null | string;
    parentObject?: null | ObjectTypeResponseModel;
    childObject?: null | ObjectTypeResponseModel;
    name: string;
    isBidirectional: boolean;
    isDependency: boolean;
};

export type RenamePartialViewRequestModel = {
    name: string;
};

export type RenameScriptRequestModel = {
    name: string;
};

export type RenameStylesheetRequestModel = {
    name: string;
};

export type ResendInviteUserRequestModel = {
    user: ReferenceByIdModel;
    message?: null | string;
};

export type ResetPasswordRequestModel = {
    email: string;
};

export type ResetPasswordTokenRequestModel = {
    password: string;
    user: ReferenceByIdModel;
    resetCode: string;
};

export type ResetPasswordUserResponseModel = {
    resetPassword?: null | string;
};

export type RuntimeLevelModel = 'Unknown' | 'Boot' | 'Install' | 'Upgrade' | 'Upgrading' | 'Run' | 'BootFailed';

export type RuntimeModeModel = 'BackofficeDevelopment' | 'Development' | 'Production';

export type SavedLogSearchRequestModel = {
    name: string;
    query: string;
};

export type SavedLogSearchResponseModel = {
    name: string;
    query: string;
};

export type ScheduleRequestModel = {
    publishTime?: null | string;
    unpublishTime?: null | string;
};

export type ScriptFolderResponseModel = {
    name: string;
    parent?: null | FileSystemFolderModel;
    path: string;
};

export type ScriptItemResponseModel = {
    isFolder: boolean;
    name: string;
    parent?: null | FileSystemFolderModel;
    path: string;
};

export type ScriptResponseModel = {
    content: string;
    name: string;
    parent?: null | FileSystemFolderModel;
    path: string;
};

export type SearcherResponseModel = {
    name: string;
};

export type SearchResultResponseModel = {
    id: string;
    score: number;
    fieldCount: number;
    fields: Array<FieldPresentationModel>;
};

export type SecurityConfigurationResponseModel = {
    passwordConfiguration: PasswordConfigurationResponseModel;
};

export type SegmentResponseModel = {
    name: string;
    alias: string;
    cultures?: null | Array<string>;
};

export type ServerConfigurationItemResponseModel = {
    name: string;
    data: string;
};

export type ServerConfigurationResponseModel = {
    allowPasswordReset: boolean;
    versionCheckPeriod: number;
    allowLocalLogin: boolean;
    umbracoCssPath: string;
    signalR: SignalRClientSettingsResponseModel;
};

export type ServerInformationResponseModel = {
    version: string;
    assemblyVersion: string;
    baseUtcOffset: string;
    runtimeMode: RuntimeModeModel;
};

export type ServerStatusResponseModel = {
    serverStatus: RuntimeLevelModel;
};

export type ServerTroubleshootingResponseModel = {
    items: Array<ServerConfigurationItemResponseModel>;
};

export type SetAvatarRequestModel = {
    file: ReferenceByIdModel;
};

export type SignalRClientSettingsResponseModel = {
    skipNegotiation: boolean;
};

export type SortingRequestModel = {
    parent?: null | ReferenceByIdModel;
    sorting: Array<ItemSortingRequestModel>;
};

export type StaticFileItemResponseModel = {
    isFolder: boolean;
    name: string;
    parent?: null | FileSystemFolderModel;
    path: string;
};

export type StatusResultTypeModel = 'Success' | 'Warning' | 'Error' | 'Info';

export type StylesheetFolderResponseModel = {
    name: string;
    parent?: null | FileSystemFolderModel;
    path: string;
};

export type StylesheetItemResponseModel = {
    isFolder: boolean;
    name: string;
    parent?: null | FileSystemFolderModel;
    path: string;
};

export type StylesheetResponseModel = {
    content: string;
    name: string;
    parent?: null | FileSystemFolderModel;
    path: string;
};

export type SubsetDataTypeTreeItemResponseModel = {
    totalBefore: number;
    totalAfter: number;
    items: Array<DataTypeTreeItemResponseModel>;
};

export type SubsetDocumentBlueprintTreeItemResponseModel = {
    totalBefore: number;
    totalAfter: number;
    items: Array<DocumentBlueprintTreeItemResponseModel>;
};

export type SubsetDocumentRecycleBinItemResponseModel = {
    totalBefore: number;
    totalAfter: number;
    items: Array<DocumentRecycleBinItemResponseModel>;
};

export type SubsetDocumentTreeItemResponseModel = {
    totalBefore: number;
    totalAfter: number;
    items: Array<DocumentTreeItemResponseModel>;
};

export type SubsetDocumentTypeTreeItemResponseModel = {
    totalBefore: number;
    totalAfter: number;
    items: Array<DocumentTypeTreeItemResponseModel>;
};

export type SubsetElementRecycleBinItemResponseModel = {
    totalBefore: number;
    totalAfter: number;
    items: Array<ElementRecycleBinItemResponseModel>;
};

export type SubsetElementTreeItemResponseModel = {
    totalBefore: number;
    totalAfter: number;
    items: Array<ElementTreeItemResponseModel>;
};

export type SubsetFileSystemTreeItemPresentationModel = {
    totalBefore: number;
    totalAfter: number;
    items: Array<FileSystemTreeItemPresentationModel>;
};

export type SubsetMediaRecycleBinItemResponseModel = {
    totalBefore: number;
    totalAfter: number;
    items: Array<MediaRecycleBinItemResponseModel>;
};

export type SubsetMediaTreeItemResponseModel = {
    totalBefore: number;
    totalAfter: number;
    items: Array<MediaTreeItemResponseModel>;
};

export type SubsetMediaTypeTreeItemResponseModel = {
    totalBefore: number;
    totalAfter: number;
    items: Array<MediaTypeTreeItemResponseModel>;
};

export type SubsetMemberTypeTreeItemResponseModel = {
    totalBefore: number;
    totalAfter: number;
    items: Array<MemberTypeTreeItemResponseModel>;
};

export type SubsetNamedEntityTreeItemResponseModel = {
    totalBefore: number;
    totalAfter: number;
    items: Array<NamedEntityTreeItemResponseModel>;
};

export type TagResponseModel = {
    id: string;
    text?: null | string;
    group?: null | string;
    nodeCount: number;
};

export type TelemetryLevelModel = 'Minimal' | 'Basic' | 'Detailed';

export type TelemetryRequestModel = {
    telemetryLevel: TelemetryLevelModel;
};

export type TelemetryResponseModel = {
    telemetryLevel: TelemetryLevelModel;
};

export type TemplateConfigurationResponseModel = {
    disabled: boolean;
};

export type TemplateItemResponseModel = {
    alias: string;
    name: string;
    id: string;
    flags: Array<FlagModel>;
};

export type TemplateQueryExecuteFilterPresentationModel = {
    propertyAlias: string;
    constraintValue: string;
    operator: OperatorModel;
};

export type TemplateQueryExecuteModel = {
    rootDocument?: null | ReferenceByIdModel;
    documentTypeAlias?: null | string;
    filters?: null | Array<TemplateQueryExecuteFilterPresentationModel>;
    sort?: null | TemplateQueryExecuteSortModel;
    take: number;
};

export type TemplateQueryExecuteSortModel = {
    propertyAlias: string;
    direction?: null | string;
};

export type TemplateQueryOperatorModel = {
    operator: OperatorModel;
    applicableTypes: Array<TemplateQueryPropertyTypeModel>;
};

export type TemplateQueryPropertyPresentationModel = {
    alias: string;
    type: TemplateQueryPropertyTypeModel;
};

export type TemplateQueryPropertyTypeModel = 'String' | 'DateTime' | 'Integer';

export type TemplateQueryResultItemPresentationModel = {
    icon: string;
    name: string;
};

export type TemplateQueryResultResponseModel = {
    queryExpression: string;
    sampleResults: Array<TemplateQueryResultItemPresentationModel>;
    resultCount: number;
    executionTime: number;
};

export type TemplateQuerySettingsResponseModel = {
    documentTypeAliases: Array<string>;
    properties: Array<TemplateQueryPropertyPresentationModel>;
    operators: Array<TemplateQueryOperatorModel>;
};

export type TemplateResponseModel = {
    id: string;
    layoutTemplate?: null | ReferenceByIdModel;
    masterTemplate?: null | ReferenceByIdModel;
    name: string;
    alias: string;
    content?: null | string;
};

export type TemporaryFileConfigurationResponseModel = {
    imageFileTypes: Array<string>;
    disallowedUploadedFilesExtensions: Array<string>;
    allowedUploadedFileExtensions: Array<string>;
    maxFileSize?: null | number;
};

export type TemporaryFileResponseModel = {
    id: string;
    availableUntil?: null | string;
    fileName: string;
};

export type TrackedReferenceDocumentTypeModel = {
    id: string;
    icon?: null | string;
    alias?: null | string;
    name?: null | string;
};

export type TrackedReferenceMediaTypeModel = {
    id: string;
    icon?: null | string;
    alias?: null | string;
    name?: null | string;
};

export type TrackedReferenceMemberTypeModel = {
    id: string;
    icon?: null | string;
    alias?: null | string;
    name?: null | string;
};

export type TreeItemKindModel = string;

export type UnlockUsersRequestModel = {
    userIds: Array<ReferenceByIdModel>;
};

export type UnpublishDocumentRequestModel = {
    cultures?: null | Array<string>;
};

export type UnpublishElementRequestModel = {
    cultures?: null | Array<string>;
};

export type UpdateCurrentUserRequestModel = {
    languageIsoCode: string;
};

export type UpdateDataTypeRequestModel = {
    name: string;
    editorAlias: string;
    editorUiAlias: string;
    values: Array<DataTypePropertyPresentationModel>;
};

export type UpdateDictionaryItemRequestModel = {
    name: string;
    translations: Array<DictionaryItemTranslationModel>;
};

export type UpdateDocumentBlueprintRequestModel = {
    values: Array<DocumentValueModel>;
    variants: Array<DocumentVariantRequestModel>;
};

export type UpdateDocumentNotificationsRequestModel = {
    subscribedActionIds: Array<string>;
};

export type UpdateDocumentRequestModel = {
    template?: null | ReferenceByIdModel;
    values: Array<DocumentValueModel>;
    variants: Array<DocumentVariantRequestModel>;
};

export type UpdateDocumentTypePropertyTypeContainerRequestModel = {
    id: string;
    parent?: null | ReferenceByIdModel;
    name?: null | string;
    type: string;
    sortOrder: number;
};

export type UpdateDocumentTypePropertyTypeRequestModel = {
    id: string;
    container?: null | ReferenceByIdModel;
    sortOrder: number;
    alias: string;
    name: string;
    description?: null | string;
    dataType: ReferenceByIdModel;
    variesByCulture: boolean;
    variesBySegment: boolean;
    validation: PropertyTypeValidationModel;
    appearance: PropertyTypeAppearanceModel;
};

export type UpdateDocumentTypeRequestModel = {
    allowedTemplates: Array<ReferenceByIdModel>;
    defaultTemplate?: null | ReferenceByIdModel;
    cleanup: DocumentTypeCleanupModel;
    allowedDocumentTypes: Array<DocumentTypeSortModel>;
    compositions: Array<DocumentTypeCompositionModel>;
    alias: string;
    name: string;
    description?: null | string;
    icon: string;
    allowedAsRoot: boolean;
    variesByCulture: boolean;
    variesBySegment: boolean;
    collection?: null | ReferenceByIdModel;
    isElement: boolean;
    allowedInLibrary: boolean;
    properties: Array<UpdateDocumentTypePropertyTypeRequestModel>;
    containers: Array<UpdateDocumentTypePropertyTypeContainerRequestModel>;
};

export type UpdateDomainsRequestModel = {
    defaultIsoCode?: null | string;
    domains: Array<DomainPresentationModel>;
};

export type UpdateElementRequestModel = {
    values: Array<ElementValueModel>;
    variants: Array<ElementVariantRequestModel>;
};

export type UpdateFolderResponseModel = {
    name: string;
};

export type UpdateLanguageRequestModel = {
    name: string;
    isDefault: boolean;
    isMandatory: boolean;
    fallbackIsoCode?: null | string;
};

export type UpdateMediaRequestModel = {
    values: Array<MediaValueModel>;
    variants: Array<MediaVariantRequestModel>;
};

export type UpdateMediaTypePropertyTypeContainerRequestModel = {
    id: string;
    parent?: null | ReferenceByIdModel;
    name?: null | string;
    type: string;
    sortOrder: number;
};

export type UpdateMediaTypePropertyTypeRequestModel = {
    id: string;
    container?: null | ReferenceByIdModel;
    sortOrder: number;
    alias: string;
    name: string;
    description?: null | string;
    dataType: ReferenceByIdModel;
    variesByCulture: boolean;
    variesBySegment: boolean;
    validation: PropertyTypeValidationModel;
    appearance: PropertyTypeAppearanceModel;
};

export type UpdateMediaTypeRequestModel = {
    allowedMediaTypes: Array<MediaTypeSortModel>;
    compositions: Array<MediaTypeCompositionModel>;
    alias: string;
    name: string;
    description?: null | string;
    icon: string;
    allowedAsRoot: boolean;
    variesByCulture: boolean;
    variesBySegment: boolean;
    collection?: null | ReferenceByIdModel;
    isElement: boolean;
    allowedInLibrary: boolean;
    properties: Array<UpdateMediaTypePropertyTypeRequestModel>;
    containers: Array<UpdateMediaTypePropertyTypeContainerRequestModel>;
};

export type UpdateMemberGroupRequestModel = {
    name: string;
};

export type UpdateMemberRequestModel = {
    email: string;
    username: string;
    oldPassword?: null | string;
    newPassword?: null | string;
    groups?: null | Array<string>;
    isApproved: boolean;
    isLockedOut: boolean;
    isTwoFactorEnabled: boolean;
    values: Array<MemberValueModel>;
    variants: Array<MemberVariantRequestModel>;
};

export type UpdateMemberTypePropertyTypeContainerRequestModel = {
    id: string;
    parent?: null | ReferenceByIdModel;
    name?: null | string;
    type: string;
    sortOrder: number;
};

export type UpdateMemberTypePropertyTypeRequestModel = {
    isSensitive: boolean;
    visibility: MemberTypePropertyTypeVisibilityModel;
    id: string;
    container?: null | ReferenceByIdModel;
    sortOrder: number;
    alias: string;
    name: string;
    description?: null | string;
    dataType: ReferenceByIdModel;
    variesByCulture: boolean;
    variesBySegment: boolean;
    validation: PropertyTypeValidationModel;
    appearance: PropertyTypeAppearanceModel;
};

export type UpdateMemberTypeRequestModel = {
    compositions: Array<MemberTypeCompositionModel>;
    alias: string;
    name: string;
    description?: null | string;
    icon: string;
    allowedAsRoot: boolean;
    variesByCulture: boolean;
    variesBySegment: boolean;
    collection?: null | ReferenceByIdModel;
    isElement: boolean;
    allowedInLibrary: boolean;
    properties: Array<UpdateMemberTypePropertyTypeRequestModel>;
    containers: Array<UpdateMemberTypePropertyTypeContainerRequestModel>;
};

export type UpdatePackageRequestModel = {
    packagePath: string;
    name: string;
    contentNodeId?: null | string;
    contentLoadChildNodes: boolean;
    mediaIds: Array<string>;
    mediaLoadChildNodes: boolean;
    documentTypes: Array<string>;
    mediaTypes: Array<string>;
    dataTypes: Array<string>;
    templates: Array<string>;
    partialViews: Array<string>;
    stylesheets: Array<string>;
    scripts: Array<string>;
    languages: Array<string>;
    dictionaryItems: Array<string>;
};

export type UpdatePartialViewRequestModel = {
    content: string;
};

export type UpdateScriptRequestModel = {
    content: string;
};

export type UpdateStylesheetRequestModel = {
    content: string;
};

export type UpdateTemplateRequestModel = {
    name: string;
    alias: string;
    content?: null | string;
};

export type UpdateUserDataRequestModel = {
    key: string;
    group: string;
    identifier: string;
    value: string;
};

export type UpdateUserGroupRequestModel = {
    name: string;
    alias: string;
    description?: null | string;
    icon?: null | string;
    sections: Array<string>;
    languages: Array<string>;
    hasAccessToAllLanguages: boolean;
    documentStartNode?: null | ReferenceByIdModel;
    documentRootAccess: boolean;
    mediaStartNode?: null | ReferenceByIdModel;
    mediaRootAccess: boolean;
    elementStartNode?: null | ReferenceByIdModel;
    elementRootAccess: boolean;
    fallbackPermissions: Array<string>;
    permissions: Array<IPermissionPresentationModel>;
};

export type UpdateUserGroupsOnUserRequestModel = {
    userIds: Array<ReferenceByIdModel>;
    userGroupIds: Array<ReferenceByIdModel>;
};

export type UpdateUserRequestModel = {
    languageIsoCode: string;
    documentStartNodeIds: Array<ReferenceByIdModel>;
    hasDocumentRootAccess: boolean;
    mediaStartNodeIds: Array<ReferenceByIdModel>;
    hasMediaRootAccess: boolean;
    elementStartNodeIds: Array<ReferenceByIdModel>;
    hasElementRootAccess: boolean;
    email: string;
    userName: string;
    name: string;
    userGroupIds: Array<ReferenceByIdModel>;
};

export type UpdateWebhookRequestModel = {
    events: Array<string>;
    enabled: boolean;
    name?: null | string;
    description?: null | string;
    url: string;
    contentTypeKeys: Array<string>;
    headers: {
        [key: string]: string;
    };
};

export type UpgradeCheckResponseModel = {
    type: string;
    comment: string;
    url: string;
};

export type UpgradeSettingsResponseModel = {
    currentState: string;
    newState: string;
    newVersion: string;
    oldVersion: string;
    reportUrl: null | string;
};

export type UserConfigurationResponseModel = {
    canInviteUsers: boolean;
    usernameIsEmail: boolean;
    passwordConfiguration: PasswordConfigurationResponseModel;
    allowChangePassword: boolean;
    allowTwoFactor: boolean;
};

export type UserDataModel = {
    group: string;
    identifier: string;
    value: string;
};

export type UserDataOperationStatusModel = 'Success' | 'NotFound' | 'UserNotFound' | 'AlreadyExists';

export type UserDataResponseModel = {
    key: string;
    group: string;
    identifier: string;
    value: string;
};

export type UserExternalLoginProviderModel = {
    providerSchemeName: string;
    providerKey: null | string;
    isLinkedOnUser: boolean;
    hasManualLinkingEnabled: boolean;
};

export type UserGroupItemResponseModel = {
    icon?: null | string;
    alias?: null | string;
    name: string;
    id: string;
    flags: Array<FlagModel>;
};

export type UserGroupResponseModel = {
    id: string;
    isDeletable: boolean;
    aliasCanBeChanged: boolean;
    name: string;
    alias: string;
    description?: null | string;
    icon?: null | string;
    sections: Array<string>;
    languages: Array<string>;
    hasAccessToAllLanguages: boolean;
    documentStartNode?: null | ReferenceByIdModel;
    documentRootAccess: boolean;
    mediaStartNode?: null | ReferenceByIdModel;
    mediaRootAccess: boolean;
    elementStartNode?: null | ReferenceByIdModel;
    elementRootAccess: boolean;
    fallbackPermissions: Array<string>;
    permissions: Array<IPermissionPresentationModel>;
};

export type UserInstallRequestModel = {
    name: string;
    email: string;
    password: string;
    subscribeToNewsletter: boolean;
};

export type UserItemResponseModel = {
    avatarUrls: Array<string>;
    kind: UserKindModel;
    name: string;
    id: string;
    flags: Array<FlagModel>;
};

export type UserKindModel = 'Default' | 'Api';

export type UserOrderModel = 'UserName' | 'Language' | 'Name' | 'Email' | 'Id' | 'CreateDate' | 'UpdateDate' | 'IsApproved' | 'IsLockedOut' | 'LastLoginDate';

export type UserPermissionModel = {
    nodeKey: string;
    permissions: Array<string>;
};

export type UserPermissionsResponseModel = {
    permissions: Array<UserPermissionModel>;
};

export type UserResponseModel = {
    id: string;
    languageIsoCode?: null | string;
    documentStartNodeIds: Array<ReferenceByIdModel>;
    hasDocumentRootAccess: boolean;
    mediaStartNodeIds: Array<ReferenceByIdModel>;
    hasMediaRootAccess: boolean;
    elementStartNodeIds: Array<ReferenceByIdModel>;
    hasElementRootAccess: boolean;
    avatarUrls: Array<string>;
    state: UserStateModel;
    failedLoginAttempts: number;
    createDate: string;
    updateDate: string;
    lastLoginDate?: null | string;
    lastLockoutDate?: null | string;
    lastPasswordChangeDate?: null | string;
    isAdmin: boolean;
    kind: UserKindModel;
    email: string;
    userName: string;
    name: string;
    userGroupIds: Array<ReferenceByIdModel>;
};

export type UserSettingsPresentationModel = {
    minCharLength: number;
    minNonAlphaNumericLength: number;
    consentLevels: Array<ConsentLevelPresentationModel>;
};

export type UserStateModel = 'Active' | 'Disabled' | 'LockedOut' | 'Invited' | 'Inactive' | 'All';

export type UserTwoFactorProviderModel = {
    providerName: string;
    isEnabledOnUser: boolean;
};

export type ValidateUpdateDocumentRequestModel = {
    cultures?: null | Array<string>;
    template?: null | ReferenceByIdModel;
    values: Array<DocumentValueModel>;
    variants: Array<DocumentVariantRequestModel>;
};

export type ValidateUpdateElementRequestModel = {
    cultures?: null | Array<string>;
    values: Array<ElementValueModel>;
    variants: Array<ElementVariantRequestModel>;
};

export type VariantItemResponseModel = {
    name: string;
    culture?: null | string;
};

export type VerifyInviteUserRequestModel = {
    user: ReferenceByIdModel;
    token: string;
};

export type VerifyInviteUserResponseModel = {
    passwordConfiguration: PasswordConfigurationResponseModel;
};

export type VerifyResetPasswordResponseModel = {
    passwordConfiguration: PasswordConfigurationResponseModel;
};

export type VerifyResetPasswordTokenRequestModel = {
    user: ReferenceByIdModel;
    resetCode: string;
};

export type WebhookEventModel = {
    eventName: string;
    eventType: string;
    alias: string;
};

export type WebhookEventResponseModel = {
    eventName: string;
    eventType: string;
    alias: string;
};

export type WebhookItemResponseModel = {
    enabled: boolean;
    name: string;
    events: string;
    url: string;
    types: string;
    id: string;
    flags: Array<FlagModel>;
};

export type WebhookLogResponseModel = {
    key: string;
    webhookKey: string;
    statusCode: string;
    isSuccessStatusCode: boolean;
    date: string;
    eventAlias: string;
    url: string;
    retryCount: number;
    requestHeaders: string;
    requestBody: string;
    responseHeaders: string;
    responseBody: string;
    exceptionOccured: boolean;
};

export type WebhookResponseModel = {
    id: string;
    events: Array<WebhookEventResponseModel>;
    enabled: boolean;
    name?: null | string;
    description?: null | string;
    url: string;
    contentTypeKeys: Array<string>;
    headers: {
        [key: string]: string;
    };
};

export type GetServerConfigurationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/server/configuration';
};

export type GetServerConfigurationResponses = {
    /**
     * OK
     */
    200: ServerConfigurationResponseModel;
};

export type GetServerConfigurationResponse = GetServerConfigurationResponses[keyof GetServerConfigurationResponses];

export type GetServerInformationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/server/information';
};

export type GetServerInformationErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetServerInformationResponses = {
    /**
     * OK
     */
    200: ServerInformationResponseModel;
};

export type GetServerInformationResponse = GetServerInformationResponses[keyof GetServerInformationResponses];

export type GetServerStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/server/status';
};

export type GetServerStatusErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type GetServerStatusError = GetServerStatusErrors[keyof GetServerStatusErrors];

export type GetServerStatusResponses = {
    /**
     * OK
     */
    200: ServerStatusResponseModel;
};

export type GetServerStatusResponse = GetServerStatusResponses[keyof GetServerStatusResponses];

export type GetServerTroubleshootingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/server/troubleshooting';
};

export type GetServerTroubleshootingErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetServerTroubleshootingResponses = {
    /**
     * OK
     */
    200: ServerTroubleshootingResponseModel;
};

export type GetServerTroubleshootingResponse = GetServerTroubleshootingResponses[keyof GetServerTroubleshootingResponses];

export type GetServerUpgradeCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/server/upgrade-check';
};

export type GetServerUpgradeCheckErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetServerUpgradeCheckResponses = {
    /**
     * OK
     */
    200: UpgradeCheckResponseModel;
};

export type GetServerUpgradeCheckResponse = GetServerUpgradeCheckResponses[keyof GetServerUpgradeCheckResponses];
