<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <VersionPrefix>17.0.2</VersionPrefix>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
  </PropertyGroup>

  <PropertyGroup>
    <Product>Umbraco.Community.WysiwgUmbracoCommunityExtensions</Product>
    <PackageId>Umbraco.Community.WysiwgUmbracoCommunityExtensions</PackageId>
    <Title>WYSIWG in the Umbraco Backoffice</Title>
    <Description>Some Block Grid editor views for the new backoffice.</Description>
    <PackageTags>umbraco;umbraco-marketplace</PackageTags>
    <Authors>Dirk Seefeld</Authors>
    <Copyright>© Dirk Seefeld, $([System.DateTime]::UtcNow.ToString(`yyyy`))</Copyright>
    <PackageProjectUrl>https://github.com/idseefeld/Wysiwg.Umbraco.Community.Extensions</PackageProjectUrl>
    <RepositoryUrl>https://github.com/idseefeld/Wysiwg.Umbraco.Community.Extensions</RepositoryUrl>
    <PackageReadmeFile>README_nuget.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <PackageIcon>logo.png</PackageIcon>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <AssemblyVersion>$(VersionPrefix)</AssemblyVersion>
    <FileVersion>$(VersionPrefix)</FileVersion>
    <Version>$(VersionPrefix)</Version>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="..\..\docs\logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  
  <ItemGroup>
    <!-- Dont include the client folder as part of packaging nuget build -->
    <Compile Remove="BlockGridStyles\**" />
    <Compile Remove="Wysiwg\**" />
    <Content Remove="BlockGridStyles\**" />
    <Content Remove="Wysiwg\**" />
    <EmbeddedResource Remove="BlockGridStyles\**" />
    <EmbeddedResource Remove="Wysiwg\**" />
    <None Remove="BlockGridStyles\**" />
    <None Remove="Wysiwg\**" />
    <Compile Remove="Composers\ApplicationLifetimeComposer.cs" />
    <Compile Remove="Models\CropModel.cs" />
    <Compile Remove="Models\ImageCropperCropExtended.cs" />
    <Content Remove="compilerconfig.json" />
    <Content Remove="Views\Partials\blockgrid\area.cshtml" />
    <Content Remove="Views\Partials\blockgrid\default.cshtml" />
    <None Remove="compilerconfig.json.defaults" />
    <None Remove="manually-pack.cmd" />
    <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>

    <!-- However make the Umbraco-package.json included for dotnet pack or nuget package and visible to the solution -->
  </ItemGroup>
  
  <ItemGroup>
    <None Include="..\..\docs\README_nuget.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="BlockGridStyles\wysiwyg-default-blockgrid.scss" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Api.Common" Version="17.0.0" />
    <PackageReference Include="Umbraco.Cms.Api.Management" Version="17.0.0" />
    <PackageReference Include="Umbraco.Cms.Web.Common" Version="17.0.0" />
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="17.0.0" />
  </ItemGroup>
  
  <!--<ItemGroup>
    <ProjectReference Include="..\..\..\..\issues\issue-20453\src\Umbraco.Cms.Api.Common\Umbraco.Cms.Api.Common.csproj" />
    <ProjectReference Include="..\..\..\..\issues\issue-20453\src\Umbraco.Cms.Api.Management\Umbraco.Cms.Api.Management.csproj" />
    <ProjectReference Include="..\..\..\..\issues\issue-20453\src\Umbraco.Web.Common\Umbraco.Web.Common.csproj" />
    <ProjectReference Include="..\..\..\..\issues\issue-20453\src\Umbraco.Web.Website\Umbraco.Web.Website.csproj" />
  </ItemGroup>-->
</Project>
