// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { CropUrlData, CropUrlError, CropUrlResponse, ImageUrlData, ImageUrlError, ImageUrlResponse, PingError, PingResponse, WhatsMyNameError, WhatsMyNameResponse, WhatsTheTimeMrWolfError, WhatsTheTimeMrWolfResponse, WhoAmIError, WhoAmIResponse } from './types.gen';

export const client = createClient(createConfig());

export class WysiwgUmbracoCommunityExtensionsService {
    public static cropUrl<ThrowOnError extends boolean = false>(options?: Options<CropUrlData, ThrowOnError>) {
        return (options?.client ?? client).get<CropUrlResponse, CropUrlError, ThrowOnError>({
            ...options,
            url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/cropurl'
        });
    }
    
    public static imageUrl<ThrowOnError extends boolean = false>(options?: Options<ImageUrlData, ThrowOnError>) {
        return (options?.client ?? client).get<ImageUrlResponse, ImageUrlError, ThrowOnError>({
            ...options,
            url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/imageurl'
        });
    }
    
    public static ping<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<PingResponse, PingError, ThrowOnError>({
            ...options,
            url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/ping'
        });
    }
    
    public static whatsMyName<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<WhatsMyNameResponse, WhatsMyNameError, ThrowOnError>({
            ...options,
            url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/whatsMyName'
        });
    }
    
    public static whatsTheTimeMrWolf<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<WhatsTheTimeMrWolfResponse, WhatsTheTimeMrWolfError, ThrowOnError>({
            ...options,
            url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/whatsTheTimeMrWolf'
        });
    }
    
    public static whoAmI<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<WhoAmIResponse, WhoAmIError, ThrowOnError>({
            ...options,
            url: '/umbraco/wysiwgumbracocommunityextensions/api/v1/whoAmI'
        });
    }
    
}